#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Brand\EditBrand.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "16a0d470cd9c7bec3cdf222d48d9a5b1b3f326a9"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_Brand_EditBrand), @"mvc.1.0.view", @"/Areas/Admin/Views/Brand/EditBrand.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/Admin/Views/Brand/EditBrand.cshtml", typeof(AspNetCore.Areas_Admin_Views_Brand_EditBrand))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 8 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Brand\EditBrand.cshtml"
using project_banhang.Models;

#line default
#line hidden
#line 10 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Brand\EditBrand.cshtml"
using System.Text;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"16a0d470cd9c7bec3cdf222d48d9a5b1b3f326a9", @"/Areas/Admin/Views/Brand/EditBrand.cshtml")]
    public class Areas_Admin_Views_Brand_EditBrand : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Brand\EditBrand.cshtml"
  
    ViewData["Title"] = "EditBrand";
    Layout = "~/Areas/Admin/Views/_share/_layout.cshtml";

#line default
#line hidden
            BeginContext(106, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(248, 247, true);
            WriteLiteral("\r\n\r\n<article class=\"content item-editor-page\">\r\n    <div class=\"title-block\">\r\n        <h3 class=\"title\">\r\n            Add new item <span class=\"sparkline bar\" data-type=\"bar\"></span>\r\n        </h3>\r\n    </div>\r\n    <form name=\"item\" method=\"post\"");
            EndContext();
            BeginWriteAttribute("action", " action=\"", 495, "\"", 523, 1);
#line 19 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Brand\EditBrand.cshtml"
WriteAttributeValue("", 504, ViewBag.FormAction, 504, 19, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(524, 33, true);
            WriteLiteral(" enctype=\"multipart/form-data\">\r\n");
            EndContext();
            BeginContext(631, 8, true);
            WriteLiteral("        ");
            EndContext();
            BeginContext(640, 23, false);
#line 21 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Brand\EditBrand.cshtml"
   Write(Html.AntiForgeryToken());

#line default
#line hidden
            EndContext();
            BeginContext(663, 354, true);
            WriteLiteral(@"
        <div class=""card card-block"">

            <!--end row-->
            <div class=""form-group row"">
                <label class=""col-sm-2 form-control-label text-xs-right""> Thương hiệu: </label>
                <div class=""col-sm-5"">
                    <input type=""text"" class=""form-control boxed"" placeholder=""Thương hiệu"" name=""brand""");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 1017, "\"", 1071, 1);
            WriteAttributeValue("", 1025, new Microsoft.AspNetCore.Mvc.Razor.HelperResult(async(__razor_attribute_value_writer) => {
                PushWriter(__razor_attribute_value_writer);
#line 28 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Brand\EditBrand.cshtml"
                                                                                                                 if (Model != null) {

#line default
#line hidden
                BeginContext(1053, 10, false);
#line 28 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Brand\EditBrand.cshtml"
                                                                                                                                      Write(Model.name);

#line default
#line hidden
                EndContext();
#line 28 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Brand\EditBrand.cshtml"
                                                                                                                                                             }

#line default
#line hidden
                PopWriter();
            }
            ), 1025, 46, false);
            EndWriteAttribute();
            BeginContext(1072, 484, true);
            WriteLiteral(@">
                </div>
            </div>
            <!--end row-->
            <!--row-->
            <div class=""form-group row"">
                <div class=""form-group row"">
                    <div class=""col-sm-10 col-sm-offset-2"">
                        <button type=""submit"" class=""btn btn-primary""> Submit </button>
                    </div>
                </div>
            </div>

            <!--end row-->

        </div>
    </form>
</article>

");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
