#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "fd6d17c5f1105255e123952ac7fa0512666266d9"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_Users_AddEditUser), @"mvc.1.0.view", @"/Areas/Admin/Views/Users/AddEditUser.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/Admin/Views/Users/AddEditUser.cshtml", typeof(AspNetCore.Areas_Admin_Views_Users_AddEditUser))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 8 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
using project_banhang.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"fd6d17c5f1105255e123952ac7fa0512666266d9", @"/Areas/Admin/Views/Users/AddEditUser.cshtml")]
    public class Areas_Admin_Views_Users_AddEditUser : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<users>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
  
    ViewData["Title"] = "AddEditUser";
    Layout = "~/Areas/Admin/Views/_share/_layout.cshtml";

#line default
#line hidden
            BeginContext(108, 4, true);
            WriteLiteral("\r\n\r\n");
            EndContext();
            BeginContext(239, 222, true);
            WriteLiteral("\r\n<div class=\"col-md-12\"\">\r\n    <div class=\"panel panel-primary\" style=\"margin-top:50px;\">\r\n        <div class=\"panel-heading\">Add edit user</div>\r\n        <div class=\"panel-body\">\r\n            <form method=\"post\" action=\"");
            EndContext();
            BeginContext(462, 18, false);
#line 16 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                   Write(ViewBag.FormAction);

#line default
#line hidden
            EndContext();
            BeginContext(480, 20, true);
            WriteLiteral("\">\r\n                ");
            EndContext();
            BeginContext(501, 23, false);
#line 17 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
           Write(Html.AntiForgeryToken());

#line default
#line hidden
            EndContext();
            BeginContext(524, 241, true);
            WriteLiteral("\r\n                <!-- rows -->\r\n                <div class=\"row\" style=\"margin-top:5px;\">\r\n                    <div class=\"col-md-2\">Name</div>\r\n                    <div class=\"col-md-10\">\r\n                        <input type=\"text\" value=\"");
            EndContext();
#line 22 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                                   if (Model != null) {

#line default
#line hidden
            BeginContext(793, 10, false);
#line 22 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                                                        Write(Model.name);

#line default
#line hidden
            EndContext();
#line 22 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                                                                               }

#line default
#line hidden
            BeginContext(811, 374, true);
            WriteLiteral(@""" name=""name"" class=""form-control"" required>
                    </div>
                </div>
                <!-- end rows -->
                <!-- rows -->
                <div class=""row"" style=""margin-top:5px;"">
                    <div class=""col-md-2"">Email</div>
                    <div class=""col-md-10"">
                        <input type=""email"" value=""");
            EndContext();
#line 30 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                                    if (Model != null) {

#line default
#line hidden
            BeginContext(1213, 11, false);
#line 30 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                                                         Write(Model.email);

#line default
#line hidden
            EndContext();
#line 30 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                                                                                 }

#line default
#line hidden
            BeginContext(1232, 411, true);
            WriteLiteral(@""" name=""email"" class=""form-control"" required>
                    </div>
                </div>
                <!-- end rows -->
                <!-- rows -->
                <div class=""row"" style=""margin-top:5px;"">
                    <div class=""col-md-2"">Password</div>
                    <div class=""col-md-10"">
                        <input type=""password"" name=""password"" class=""form-control"" ");
            EndContext();
#line 38 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                                                                     if (Model != null) { 

#line default
#line hidden
            BeginContext(1671, 77, true);
            WriteLiteral(" placeholder=\"Không đổi password thì không nhập thông tin vào ô textbox này\" ");
            EndContext();
#line 38 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                                                                                                                                                                                      } else { 

#line default
#line hidden
            BeginContext(1772, 9, true);
            WriteLiteral(" required");
            EndContext();
#line 38 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\AddEditUser.cshtml"
                                                                                                                                                                                                                                      }

#line default
#line hidden
            BeginContext(1790, 650, true);
            WriteLiteral(@" title=""Không đổi password thì không nhập thông tin vào ô textbox này"">
                    </div>
                </div>
                <!-- end rows -->
                <!-- rows -->
                <div class=""row"" style=""margin-top:5px;"">
                    <div class=""col-md-2""></div>
                    <div class=""col-md-10"">
                        <input type=""submit"" value=""Xác nhận"" class=""btn btn-primary"">
                    </div>
                </div>
                <!-- end rows -->
            </form>
        </div>
    </div>
</div>
<style>
    form input{
        width:100px;
    }
</style>




");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<users> Html { get; private set; }
    }
}
#pragma warning restore 1591
