#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c1077d59f1f8053ba7352d27d91505fc50b2e50a"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_Users_List), @"mvc.1.0.view", @"/Areas/Admin/Views/Users/List.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/Admin/Views/Users/List.cshtml", typeof(AspNetCore.Areas_Admin_Views_Users_List))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 8 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
using project_banhang.Models;

#line default
#line hidden
#line 10 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
using X.PagedList.Mvc.Core;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"c1077d59f1f8053ba7352d27d91505fc50b2e50a", @"/Areas/Admin/Views/Users/List.cshtml")]
    public class Areas_Admin_Views_Users_List : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<X.PagedList.IPagedList<users>>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
  
    ViewData["Title"] = "List";
    Layout = "~/Areas/Admin/Views/_share/_layout.cshtml";

#line default
#line hidden
            BeginContext(101, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(327, 3506, true);
            WriteLiteral(@"
    <article class=""content items-list-page"">
        <div class=""title-search-block"">
            <div class=""title-block"">
                <div class=""row"">
                    <div class=""col-md-6"">
                        <h3 class=""title"">
                            Items <a href=""/Admin/Users/Add"" class=""btn btn-primary btn-sm rounded-s""> Add New </a>
                            <!----> -->
                            <div class=""action dropdown"">
                                <button class=""btn  btn-sm rounded-s btn-secondary dropdown-toggle"" type=""button"" id=""dropdownMenu1"" data-toggle=""dropdown"" aria-haspopup=""true"" aria-expanded=""false""> More actions... </button>
                                <div class=""dropdown-menu"" aria-labelledby=""dropdownMenu1"">
                                    <a class=""dropdown-item"" href=""https://modularcode.io/modular-admin-html/items-list.html#""><i class=""fa fa-pencil-square-o icon""></i>Mark as a draft</a>
                                    <a class");
            WriteLiteral(@"=""dropdown-item"" href=""https://modularcode.io/modular-admin-html/items-list.html#"" data-toggle=""modal"" data-target=""#confirm-modal""><i class=""fa fa-close icon""></i>Delete</a>
                                </div>
                            </div>
                        </h3>
                        <p class=""title-description""> List of sample items - e.g. books, movies, events, etc... </p>
                    </div>
                </div>
            </div>
            <div class=""items-search"">
                <form class=""form-inline"">
                    <div class=""input-group"">
                        <input type=""text"" class=""form-control boxed rounded-s"" placeholder=""Search for..."" style=""height:33px"">
                        <span class=""input-group-btn"">
                            <button class=""btn btn-secondary rounded-s"" type=""button"">
                                <i class=""fa fa-search""></i>
                            </button>
                        </span>
            ");
            WriteLiteral(@"        </div>
                </form>
            </div>
        </div>
        <div class=""card items"">
            <ul class=""item-list striped"">
                <li class=""item item-list-header"">
                    <div class=""item-row"">
                        <div class=""item-col fixed item-col-check"">
                            <label class=""item-check"" id=""select-all-items"">
                                <input type=""checkbox"" class=""checkbox"">
                                <span></span>
                            </label>
                        </div>

                        <div class=""item-col item-col-header item-col-title"">
                            <div>
                                <span>Name</span>
                            </div>
                        </div>

                        <div class=""item-col item-col-header item-col-title"">
                            <div>
                                <span>Email</span>
                            </di");
            WriteLiteral(@"v>
                        </div>

                        <div class=""item-col item-col-header fixed item-col-actions-dropdown"">
                        </div>
                        <div class=""item-col fixed item-col-actions-dropdown"">
                            <div class=""item-actions-dropdown"">

                            </div>
                        </div>
                    </div>
                </li>

");
            EndContext();
#line 80 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
                 foreach (var item in Model)
                {

#line default
#line hidden
            BeginContext(3898, 632, true);
            WriteLiteral(@"                    <li class=""item item-list-header"">
                        <div class=""item-row"">
                            <div class=""item-col fixed item-col-check"">
                                <label class=""item-check"" id=""select-all-items"">
                                    <input type=""checkbox"" class=""checkbox"">
                                    <span></span>
                                </label>
                            </div>

                            <div class=""item-col item-col-header item-col-title"">
                                <div>
                                    <span>");
            EndContext();
            BeginContext(4531, 9, false);
#line 93 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
                                     Write(item.name);

#line default
#line hidden
            EndContext();
            BeginContext(4540, 251, true);
            WriteLiteral("</span>\r\n                                </div>\r\n                            </div>\r\n\r\n                            <div class=\"item-col item-col-header item-col-title\">\r\n                                <div>\r\n                                    <span>");
            EndContext();
            BeginContext(4792, 10, false);
#line 99 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
                                     Write(item.email);

#line default
#line hidden
            EndContext();
            BeginContext(4802, 1103, true);
            WriteLiteral(@"</span>
                                </div>
                            </div>

                            <div class=""item-col item-col-header fixed item-col-actions-dropdown""></div>
                            <div class=""item-col fixed item-col-actions-dropdown"">
                                <div class=""item-actions-dropdown"">
                                    <a class=""item-actions-toggle-btn"">
                                        <span class=""inactive"">
                                            <i class=""fa fa-cog""></i>
                                        </span>
                                        <span class=""active"">
                                            <i class=""fa fa-chevron-circle-right""></i>
                                        </span>
                                    </a>
                                    <div class=""item-actions-block"">
                                        <ul class=""item-actions-list"">
                                    ");
            WriteLiteral("        <li>\r\n                                                <a class=\"remove\"");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 5905, "\"", 5943, 2);
            WriteAttributeValue("", 5912, "/Admin/Users/Delete?id=", 5912, 23, true);
#line 117 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
WriteAttributeValue("", 5935, item.id, 5935, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(5944, 355, true);
            WriteLiteral(@" onclick=""return window.confirm('Are you sure?');"">
                                                    <i class=""fa fa-trash-o ""></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a class=""edit""");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 6299, "\"", 6335, 2);
            WriteAttributeValue("", 6306, "/Admin/Users/Edit?id=", 6306, 21, true);
#line 122 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
WriteAttributeValue("", 6327, item.id, 6327, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(6336, 416, true);
            WriteLiteral(@">
                                                    <i class=""fa fa-pencil""></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
");
            EndContext();
#line 132 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
                }

#line default
#line hidden
            BeginContext(6771, 16, true);
            WriteLiteral("                ");
            EndContext();
            BeginContext(6788, 77, false);
#line 133 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
           Write(Html.PagedListPager(Model, page => Url.Action("List", "Users", new { page })));

#line default
#line hidden
            EndContext();
            BeginContext(6865, 566, true);
            WriteLiteral(@"
            </ul>
        </div>
    </article>

<!--<div class=""col-md-12"">
    <div style=""margin-bottom:5px;"">
        <a href=""/Admin/Users/Add"" class=""btn btn-primary"">Add user</a>
    </div>
    <div class=""panel panel-primary"">
        <div class=""panel-heading"">List User</div>
        <div class=""panel-body"">
            <table class=""table table-bordered table-hover"">
                <tr>
                    <th>Fullname</th>
                    <th>Email</th>
                    <th style=""width:100px;""></th>
                </tr>
");
            EndContext();
#line 151 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
                 foreach (var item in Model)
                {

#line default
#line hidden
            BeginContext(7496, 54, true);
            WriteLiteral("                    <tr>\r\n                        <td>");
            EndContext();
            BeginContext(7551, 9, false);
#line 154 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
                       Write(item.name);

#line default
#line hidden
            EndContext();
            BeginContext(7560, 35, true);
            WriteLiteral("</td>\r\n                        <td>");
            EndContext();
            BeginContext(7596, 10, false);
#line 155 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
                       Write(item.email);

#line default
#line hidden
            EndContext();
            BeginContext(7606, 105, true);
            WriteLiteral("</td>\r\n                        <td style=\"text-align:center;width:200px\">\r\n                            <a");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 7711, "\"", 7747, 2);
            WriteAttributeValue("", 7718, "/Admin/Users/Edit?id=", 7718, 21, true);
#line 157 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
WriteAttributeValue("", 7739, item.id, 7739, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(7748, 47, true);
            WriteLiteral(">Edit</a>&nbsp;\r\n                            <a");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 7795, "\"", 7833, 2);
            WriteAttributeValue("", 7802, "/Admin/Users/Delete?id=", 7802, 23, true);
#line 158 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
WriteAttributeValue("", 7825, item.id, 7825, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(7834, 121, true);
            WriteLiteral(" onclick=\"return window.confirm(\'Are you sure?\');\">Delete</a>\r\n                        </td>\r\n                    </tr>\r\n");
            EndContext();
#line 161 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
                }

#line default
#line hidden
            BeginContext(7974, 22, true);
            WriteLiteral("            </table>\r\n");
            EndContext();
            BeginContext(8181, 12, true);
            WriteLiteral("            ");
            EndContext();
            BeginContext(8194, 77, false);
#line 166 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Users\List.cshtml"
       Write(Html.PagedListPager(Model, page => Url.Action("List", "Users", new { page })));

#line default
#line hidden
            EndContext();
            BeginContext(8271, 43, true);
            WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>-->\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<X.PagedList.IPagedList<users>> Html { get; private set; }
    }
}
#pragma warning restore 1591
