#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "84d67cae7359d1bfdd63893e1f8875bf328e62e9"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_Order_Index), @"mvc.1.0.view", @"/Areas/Admin/Views/Order/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/Admin/Views/Order/Index.cshtml", typeof(AspNetCore.Areas_Admin_Views_Order_Index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
#line 14 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
using System.Linq;

#line default
#line hidden
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 8 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
using project_banhang.Models;

#line default
#line hidden
#line 10 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
using X.PagedList.Mvc.Core;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"84d67cae7359d1bfdd63893e1f8875bf328e62e9", @"/Areas/Admin/Views/Order/Index.cshtml")]
    public class Areas_Admin_Views_Order_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<X.PagedList.IPagedList<order>>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
  
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/_share/_layout.cshtml";

#line default
#line hidden
            BeginContext(102, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(382, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 16 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
  
    DataContext db = new DataContext();

    var infor = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");


#line default
#line hidden
            BeginContext(511, 3227, true);
            WriteLiteral(@"
<article class=""content responsive-tables-page"">
    <div class=""title-block"">
        <h1 class=""title""> Đơn hàng </h1>

    </div>
    <section class=""section"">
        <div class=""row"">
            <div class=""col-md-12"">
                <div class=""card"">
                    <ul class=""item-list striped"">
                        <li class=""item item-list-header"">
                            <div class=""item-row"">

                                <div class=""item-col item-col-header item-col-title"">
                                    <div>
                                        <span>Mã đơn hàng</span>
                                    </div>
                                </div>

                                <div class=""item-col item-col-header name"">
                                    <div class=""no-overflow"">
                                        <span>Tên khách hàng</span>
                                    </div>
                                </div>

          ");
            WriteLiteral(@"                      <div class=""item-col item-col-header address"">
                                    <div class=""no-overflow"">
                                        <span>Địa chỉ</span>
                                    </div>
                                </div>

                                <div class=""item-col item-col-header item-price"">
                                    <div class=""no-overflow"">
                                        <span>Giá trị đơn hàng</span>
                                    </div>
                                </div>

                                <div class=""item-col item-col-header item-col-title"">
                                    <div>
                                        <span>Trạng thái thanh toán</span>
                                    </div>
                                </div>

                                <div class=""item-col item-col-header item-col-title"">
                                    <div>
                  ");
            WriteLiteral(@"                      <span>Trạng thái đơn hàng</span>
                                    </div>
                                </div>

                                <div class=""item-col item-col-header date"">
                                    <div class=""no-overflow"">
                                        <span>Ghi chú</span>
                                    </div>
                                </div>

                                <div class=""item-col item-col-header date"">
                                    <div class=""no-overflow"">
                                        <span>Ngày tạo</span>
                                    </div>
                                </div>

                                <div class=""item-col item-col-header fixed item-col-actions-dropdown"">
                                </div>
                                <div class=""item-col fixed item-col-actions-dropdown"">
                                    <div class=""item-actions-dropdown"">
");
            WriteLiteral("\r\n                                    </div>\r\n                                </div>\r\n                            </div>\r\n                        </li>\r\n\r\n");
            EndContext();
#line 94 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                         foreach (var item in Model)
                        {

#line default
#line hidden
            BeginContext(3819, 311, true);
            WriteLiteral(@"                            <li class=""item item-list-header"">
                                <div class=""item-row"">

                                    <div class=""item-col item-col-header item-col-title"">
                                        <div>
                                            <span>#");
            EndContext();
            BeginContext(4131, 7, false);
#line 101 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                              Write(item.id);

#line default
#line hidden
            EndContext();
            BeginContext(4138, 306, true);
            WriteLiteral(@" HL</span>
                                        </div>
                                    </div>

                                    <div class=""item-col item-col-header name"">
                                        <div class=""no-overflow"">
                                            <span>
");
            EndContext();
#line 108 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                                  
                                                    int _id = item.id_customer;
                                                    

#line default
#line hidden
            BeginContext(4636, 62, false);
#line 110 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                                     Write(db.customers.Where(tbl => tbl.id == _id).FirstOrDefault().name);

#line default
#line hidden
            EndContext();
            BeginContext(4758, 348, true);
            WriteLiteral(@"                                            </span>
                                        </div>
                                    </div>

                                    <div class=""item-col item-col-header address"">
                                        <div class=""no-overflow"">
                                            <span>");
            EndContext();
            BeginContext(5107, 12, false);
#line 118 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                             Write(item.address);

#line default
#line hidden
            EndContext();
            BeginContext(5119, 307, true);
            WriteLiteral(@"</span>
                                        </div>
                                    </div>

                                    <div class=""item-col item-col-header item-price"">
                                        <div class=""no-overflow"">
                                            <span>");
            EndContext();
            BeginContext(5427, 47, false);
#line 124 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                             Write(string.Format(infor, "{0:c0" + "}", item.price));

#line default
#line hidden
            EndContext();
            BeginContext(5474, 291, true);
            WriteLiteral(@"</span>
                                        </div>
                                    </div>

                                    <div class=""item-col item-col-header item-col-title"">
                                        <div>
                                            <span>");
            EndContext();
            BeginContext(5766, 19, false);
#line 130 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                             Write(item.status_payment);

#line default
#line hidden
            EndContext();
            BeginContext(5785, 303, true);
            WriteLiteral(@"</span>
                                        </div>
                                    </div>

                                    <div class=""item-col item-col-header date"">
                                        <div class=""no-overflow"">
                                            <span>
");
            EndContext();
#line 137 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                                 if (item.status == false)
                                                {
                                                    

#line default
#line hidden
            BeginContext(6273, 14, true);
            WriteLiteral("Đang giao hàng");
            EndContext();
#line 139 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                                                               
                                                }
                                                else
                                                {
                                                    

#line default
#line hidden
            BeginContext(6510, 12, true);
            WriteLiteral("Đã nhận hàng");
            EndContext();
#line 143 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                                                             
                                                }

#line default
#line hidden
            BeginContext(6582, 345, true);
            WriteLiteral(@"                                            </span>
                                        </div>
                                    </div>

                                    <div class=""item-col item-col-header date"">
                                        <div class=""no-overflow"">
                                            <span>");
            EndContext();
            BeginContext(6928, 9, false);
#line 151 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                             Write(item.note);

#line default
#line hidden
            EndContext();
            BeginContext(6937, 301, true);
            WriteLiteral(@"</span>
                                        </div>
                                    </div>

                                    <div class=""item-col item-col-header date"">
                                        <div class=""no-overflow"">
                                            <span>");
            EndContext();
            BeginContext(7239, 12, false);
#line 157 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                             Write(item.created);

#line default
#line hidden
            EndContext();
            BeginContext(7251, 1108, true);
            WriteLiteral(@"</span>
                                        </div>
                                    </div>

                                    <div class=""item-col item-col-header fixed item-col-actions-dropdown""></div>
                                    <div class=""item-col fixed item-col-actions-dropdown"">
                                        <div class=""item-actions-dropdown"">
                                            <a class=""item-actions-toggle-btn"">
                                                <span class=""inactive"">
                                                    <i class=""fa fa-cog""></i>
                                                </span>
                                                <span class=""active"">
                                                    <i class=""fa fa-chevron-circle-right""></i>
                                                </span>
                                            </a>
                                            <div class=""item-actions-block");
            WriteLiteral("\">\r\n                                                <ul class=\"item-actions-list\">\r\n");
            EndContext();
#line 174 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                                     if (!item.status)
                                                    {

#line default
#line hidden
            BeginContext(8486, 137, true);
            WriteLiteral("                                                        <li>\r\n                                                            <a class=\"edit\"");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 8623, "\"", 8662, 2);
            WriteAttributeValue("", 8630, "/Admin/Order/Comfirm?id=", 8630, 24, true);
#line 177 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
WriteAttributeValue("", 8654, item.id, 8654, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(8663, 262, true);
            WriteLiteral(@" title=""Xác nhận đã giao hàng"">
                                                                <i class=""fa fa-check-circle""></i>
                                                            </a>
                                                        </li>
");
            EndContext();
#line 181 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                                                    }

#line default
#line hidden
            BeginContext(8980, 131, true);
            WriteLiteral("                                                    <li>\r\n                                                        <a class=\"remove\"");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 9111, "\"", 9149, 2);
            WriteAttributeValue("", 9118, "/Admin/Order/Delete?id=", 9118, 23, true);
#line 183 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
WriteAttributeValue("", 9141, item.id, 9141, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(9150, 416, true);
            WriteLiteral(@" onclick=""return window.confirm('Are you sure?');"" title=""Hủy đơn hàng"">
                                                            <i class=""fa fa-trash-o ""></i>
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a class=""edit""");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 9566, "\"", 9604, 2);
            WriteAttributeValue("", 9573, "/Admin/Order/Detail?id=", 9573, 23, true);
#line 188 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
WriteAttributeValue("", 9596, item.id, 9596, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(9605, 514, true);
            WriteLiteral(@" title=""Chi tiết đơn hàng"">
                                                            <i class=""fa fa-pencil""></i>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
");
            EndContext();
#line 198 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                        }

#line default
#line hidden
            BeginContext(10146, 24, true);
            WriteLiteral("                        ");
            EndContext();
            BeginContext(10171, 78, false);
#line 199 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\Order\Index.cshtml"
                   Write(Html.PagedListPager(Model, page => Url.Action("Index", "order", new { page })));

#line default
#line hidden
            EndContext();
            BeginContext(10249, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(10387, 105, true);
            WriteLiteral("                    </ul>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </section>\r\n\r\n");
            EndContext();
            BeginContext(17472, 14, true);
            WriteLiteral("</article>\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<X.PagedList.IPagedList<order>> Html { get; private set; }
    }
}
#pragma warning restore 1591
