#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "b705dfa750a6772edaac1df86f4da584ee75d415"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Cart_Checkout), @"mvc.1.0.view", @"/Views/Cart/Checkout.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Cart/Checkout.cshtml", typeof(AspNetCore.Views_Cart_Checkout))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"b705dfa750a6772edaac1df86f4da584ee75d415", @"/Views/Cart/Checkout.cshtml")]
    public class Views_Cart_Checkout : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("shortcut icon"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/images/favicon-16x16.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("type", new global::Microsoft.AspNetCore.Html.HtmlString("image/x-icon"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memoryzone-Checkout/bootstrap.min.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("type", new global::Microsoft.AspNetCore.Html.HtmlString("text/css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memoryzone-Checkout/nprogress.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_7 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memoryzone-Checkout/font-awesome.min.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_8 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memoryzone-Checkout/select2-min.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_9 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memoryzone-Checkout/checkout.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_10 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memoryzone-Checkout/checkout(1).css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_11 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("logo__image  logo__image--small "), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_12 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("alt", new global::Microsoft.AspNetCore.Html.HtmlString("Memoryzone - Professional in memory"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_13 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memoryzone-Checkout/checkout_logo.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_14 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("product-thumbnail__image"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_15 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("style", new global::Microsoft.AspNetCore.Html.HtmlString("border: 0px; width: 100%; height: 100%;"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_16 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memoryzone-Checkout/saved_resource.html"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_17 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memoryzone-Checkout/barcode-zalo.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_18 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("zalopay-qr-payment-icon"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_19 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("body--custom-background-color "), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 1 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
  
    Layout = null;

#line default
#line hidden
            BeginContext(27, 212, true);
            WriteLiteral("\r\n<!DOCTYPE html>\r\n<!-- saved from url=(0071)https://www.memoryzone.com.vn/checkout/b48688c051364efd970825ea2d6d992c -->\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" class=\"anyflexbox boxshadow display-table\">\r\n\r\n");
            EndContext();
            BeginContext(239, 7299, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "f457bba93cd6403fb10a2c6fec5af753", async() => {
                BeginContext(245, 2570, true);
                WriteLiteral(@"
    <meta http-equiv=""Content-Type"" content=""text/html; charset=UTF-8"">
    <!-- Font Awesome5  -->
    <script src=""https://kit.fontawesome.com/yourcode.js""></script>
    <!-- end font awesome5 -->
    <!-- End Jeoway Analytics Code -->
    <!-- <script type=""text/javascript"" async="""" src=""~/Memoryzone-Checkout/f.txt""></script> -->
    <!-- <script type=""text/javascript"" async="""" src=""~/Memoryzone-Checkout/analytics.js.tải xuống""></script> -->
    <!-- <script type=""text/javascript"" async="""" src=""~/Memoryzone-Checkout/f.txt""></script>
    <script type=""text/javascript"" async="""" src=""~/Memoryzone-Checkout/analytics.js.tải xuống""></script>
    <script type=""text/javascript"" async="""" defer="""" src=""~/Memoryzone-Checkout/matomo.js.tải xuống""></script> -->
    <!-- <script type=""text/javascript"">
        var _paq = window._paq || [];
        var euser = getCookie(""euser"");
        if (euser != """") {
            _paq.push(['setUserId', euser]);
        }
        _paq.push(['trackPageView']);
    ");
                WriteLiteral(@"    _paq.push(['enableLinkTracking']);

        var visitor_id;
        _paq.push([function() {
            visitor_id = this.getVisitorId();
        }]);

        (function() {
            var u = ""https://analytics.jeoway.com/"";
            _paq.push(['setTrackerUrl', u + 'js/tracker.php']);
            _paq.push(['setSiteId', '7']);
            var d = document,
                g = d.createElement('script'),
                s = d.getElementsByTagName('script')[0];
            g.type = 'text/javascript';
            g.async = true;
            g.defer = true;
            g.src = u + 'js/tracker.php';
            s.parentNode.insertBefore(g, s);
        })();
    </script> -->
    <!-- Jeoway Analytics -->
    <!-- <script type=""text/javascript"">
        function getCookie(cname) {
            var name = cname + ""="";
            var ca = document.cookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) =");
                WriteLiteral(@"= ' ') {
                    c = c.substring(1);
                }
                if (c.indexOf(name) == 0) {
                    return c.substring(name.length, c.length);
                }
            }
            return """";
        }
    </script> -->

    <meta http-equiv=""X-UA-Compatible"" content=""IE=edge,chrome=1"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1"">
    <meta name=""description"" content=""Thanh toán đơn hàng"">

    <title>Thanh toán đơn hàng</title>


    ");
                EndContext();
                BeginContext(2815, 80, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "b531309b86094fd59da9bd0620a5df7b", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(2895, 4, true);
                WriteLiteral("\r\n\r\n");
                EndContext();
                BeginContext(3302, 25, true);
                WriteLiteral("    <style></style>\r\n    ");
                EndContext();
                BeginContext(3327, 86, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "46191df6b7e2464895e51e798722763e", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(3413, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(3419, 82, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "3b277c37b9c34ee1b8042545cd0dc4d1", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_6);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(3501, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(3507, 89, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "2425d799ea8647a5a6ae28fec4913eb3", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_7);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(3596, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(3602, 84, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "bf744cc2fb304df1abb788c17ab879bb", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_8);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(3686, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(3692, 81, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "68409641978c42f9ba5e969ba0d48d56", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_9);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(3773, 6, true);
                WriteLiteral("\r\n    ");
                EndContext();
                BeginContext(3779, 84, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "66de1e7c40ae45e18e60ca5042d74947", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_10);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(3863, 3668, true);
                WriteLiteral(@"


    <!--Facebook Pixel Code-->
    <!-- <script>
            ! function(f, b, e, v, n, t, s) {
                if (f.fbq) return;
                n = f.fbq = function() {
                    n.callMethod ?
                        n.callMethod.apply(n, arguments) : n.queue.push(arguments)
                };
                if (!f._fbq) f._fbq = n;
                n.push = n;
                n.loaded = !0;
                n.version = '2.0';
                n.queue = [];
                t = b.createElement(e);
                t.async = !0;
                t.src = v;
                s = b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t, s)
            }
            (window,
                document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '555390224831405', {
                'em': 'admin1@email.com',
                'ph': '0378491006',
                'fn': 'Nguyễn Hòa'
            }, {
                'agent': 'p");
                WriteLiteral(@"lsapo'
            }); // Insert your pixel ID here.
            fbq('track', 'PageView');
        </script>
        <noscript><img height = '1' width = '1' style = 'display:none'
    src = 'https://www.facebook.com/tr?id=555390224831405&ev=PageView&noscript=1'
    /></noscript> -->
    <!--DO NOT MODIFY-->
    <!--End Facebook Pixel Code-->
    <!-- <script>
        var Bizweb = Bizweb || {};
        Bizweb.store = 'memoryzone-com-vn.mysapo.net';
        Bizweb.theme = {
            ""id"": 681013,
            ""role"": ""main"",
            ""name"": ""Cocomart (Main)""
        };
        Bizweb.template = '';
    </script> -->
    <!-- <script type=""text/javascript"">
        if (typeof Bizweb == 'undefined') {
            Bizweb = {};
        }
        Bizweb.Checkout = {};
        Bizweb.Checkout.token = ""b48688c051364efd970825ea2d6d992c"";
        Bizweb.Checkout.apiHost = ""memoryzone-com-vn.mysapo.net"";
    </script> -->
    <!-- <script>
        fbq('track', 'InitiateCheckout', {
    ");
                WriteLiteral(@"        content_ids: ['12665627'],
            content_name: 'SSD Crucial BX500 3D NAND SATA III 2.5 inch 120GB  CT120BX500SSD1',
            value: '499000.0000',
            num_items: '1',
            content_type: 'product',
            currency: 'VND'
        });
    </script>
    <script type=""text/javascript"">
        $('#add-to-cart-form > div.form-group.form_button_details.margin-top-5 > div > div.button_actions.clearfix > button').click(function() {
            var tensp = $('.title-product').text();
            var giasp = $('meta[itemprop=price]').attr(""content"");
            _paq.push(['trackEvent', 'DatHang', 'ClickDatHang', tensp, giasp]);
        });
    </script>
    <script type=""text/javascript"">
        $('.xem_nhanh').click(function() {
            _paq.push(['trackEvent', 'XemNhanh', 'ClickXemNhanhAllSite']);
        });
    </script>
    <script type=""text/javascript"">
        $(document).ready(function() {
            $("".more-text"").click(function() {
          ");
                WriteLiteral(@"      _paq.push(['trackEvent', 'TrangNoiDung', 'ClickXemThemContent']);
            });
        });
    </script>
    <script type=""text/javascript"">
        $(document).ready(function() {
            $('.btn_call').click(function() {
                _paq.push(['trackGoal', 3]);
            });
        });
    </script>
    <script src=""~/Memoryzone-Checkout/f(1).txt""></script>
    <script src=""~/Memoryzone-Checkout/f(2).txt""></script>
    <style>
        #moca-modal {
            opacity: 1 !important;
            overflow: visible !important
        }
    </style> -->
");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(7538, 4, true);
            WriteLiteral("\r\n\r\n");
            EndContext();
            BeginContext(7542, 69016, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "a4514e923c0b45b681df35f6c8558169", async() => {
                BeginContext(7587, 176, true);
                WriteLiteral("\r\n    <div class=\"banner\" data-header=\"\">\r\n        <div class=\"wrap\">\r\n            <div class=\"shop logo logo--left \">\r\n\r\n                <a href=\"/Home\">\r\n                    ");
                EndContext();
                BeginContext(7763, 134, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "093b40bc2f104bcd9ba7d61dd8194447", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_11);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_12);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_13);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(7897, 1040, true);
                WriteLiteral(@"
                </a>

            </div>
        </div>
    </div>
    <button class=""order-summary-toggle"" bind-event-click=""Bizweb.StoreCheckout.toggleOrderSummary(this)"">
        <div class=""wrap"">
            <h2>
                <label class=""control-label"">Đơn hàng</label>
                <label class=""control-label hidden-small-device"">
                    (1 sản phẩm)
                </label>
                <label class=""control-label visible-small-device inline"">
                    (1)
                </label>
            </h2>
            <a class=""underline-none expandable pull-right"" href=""javascript:void(0)"">
                Xem chi tiết
            </a>
        </div>
    </button>










    <div context=""paymentStatus"" define=""{ paymentStatus: new Bizweb.PaymentStatus(this,{payment_processing:&quot;&quot;,payment_provider_id:&quot;&quot;,payment_info:{} }) }"">

    </div>
    <form method=""post"" action=""/Cart/Order"" class=""content stateful-form formChec");
                WriteLiteral("kout\">\r\n        ");
                EndContext();
                BeginContext(8938, 23, false);
#line 229 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
   Write(Html.AntiForgeryToken());

#line default
#line hidden
                EndContext();
                BeginContext(8961, 939, true);
                WriteLiteral(@"
        <div class=""wrap"" context=""checkout"" define=""{checkout: new Bizweb.StoreCheckout(this,{ token: &quot;b48688c051364efd970825ea2d6d992c&quot;, email: &quot;admin1@email.com&quot;, totalOrderItemPrice: 499000.0000, shippingFee: 0, freeShipping: false, requiresShipping: true, existCode: false, code: &quot;&quot;, discount: 0, settingLanguage: &quot;vi&quot;, moneyFormat: &quot;{{amount_no_decimals_with_comma_separator}}₫&quot;, discountLabel: &quot;Miễn phí&quot;, districtPolicy: &quot;optional&quot;, wardPolicy: &quot;hidden&quot;, district: &quot;&quot;, ward: &quot;&quot;, province:&quot;&quot;, otherAddress: false, shippingId: 0, shippingMethods: [], customerAddressId: 14327956, reductionCode: &quot;&quot; })}""
             data-select2-id=""14"">
            <div class=""sidebar "">
                <div class=""sidebar_header"">
                    <h2>
                        <label class=""control-label"">Đơn hàng (");
                EndContext();
                BeginContext(9901, 13, false);
#line 235 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                          Write(ViewBag.count);

#line default
#line hidden
                EndContext();
                BeginContext(9914, 269, true);
                WriteLiteral(@" sản phẩm)</label>
                    </h2>
                    <hr class=""full_width"">
                </div>
                <div class=""sidebar__content"">
                    <div class=""order-summary order-summary--product-list order-summary--is-collapsed"">
");
                EndContext();
#line 241 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                          
                            var infor = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
                        

#line default
#line hidden
                BeginContext(10337, 24, true);
                WriteLiteral("                        ");
                EndContext();
#line 244 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                         foreach (var item in ViewBag._cart)
                        {

#line default
#line hidden
                BeginContext(10426, 666, true);
                WriteLiteral(@"                            <div class=""summary-body summary-section summary-product"">
                                <div class=""summary-product-list"">
                                    <table class=""product-table"">
                                        <tbody>

                                            <tr class=""product product-has-image clearfix"">
                                                <td>
                                                    <div class=""product-thumbnail"">
                                                        <div class=""product-thumbnail__wrapper"">

                                                            ");
                EndContext();
                BeginContext(11092, 84, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "2b1801fa562b4876a97e5c7a63ac8950", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                AddHtmlAttributeValue("", 11102, "~/Upload/Products/", 11102, 18, true);
#line 256 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
AddHtmlAttributeValue("", 11120, item.ItemsList.media, 11120, 21, false);

#line default
#line hidden
                EndAddHtmlAttributeValues(__tagHelperExecutionContext);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_14);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(11176, 185, true);
                WriteLiteral("\r\n\r\n                                                        </div>\r\n                                                        <span class=\"product-thumbnail__quantity\" aria-hidden=\"true\">");
                EndContext();
                BeginContext(11362, 13, false);
#line 259 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                                                                                Write(item.quantity);

#line default
#line hidden
                EndContext();
                BeginContext(11375, 343, true);
                WriteLiteral(@"</span>
                                                    </div>
                                                </td>
                                                <td class=""product-info"">
                                                    <span class=""product-info-name"">

                                                        ");
                EndContext();
                BeginContext(11719, 19, false);
#line 265 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                   Write(item.ItemsList.name);

#line default
#line hidden
                EndContext();
                BeginContext(11738, 263, true);
                WriteLiteral(@"
                                                    </span>


                                                </td>
                                                <td class=""product-price text-right"">

                                                    ");
                EndContext();
                BeginContext(12002, 57, false);
#line 272 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                               Write(string.Format(infor, "{0:c0" + "}", item.ItemsList.price));

#line default
#line hidden
                EndContext();
                BeginContext(12059, 571, true);
                WriteLiteral(@"
                                                </td>
                                            </tr>

                                        </tbody>
                                    </table>
                                    <div class=""order-summary__scroll-indicator"">
                                        Cuộn chuột để xem thêm
                                        <i class=""fa fa-long-arrow-down"" aria-hidden=""true""></i>
                                    </div>
                                </div>
                            </div>
");
                EndContext();
#line 284 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                        }

#line default
#line hidden
                BeginContext(12657, 3181, true);
                WriteLiteral(@"                        <hr class=""m0"">
                    </div>
                    <div class=""order-summary order-summary--discount"">
                        <div class=""summary-section"">
                            <div class=""form-group m0"" bind-show=""!existCode || !applyWithPromotion || code == null || !code.length"">
                                <div class=""field__input-btn-wrapper"">
                                    <div class=""field__input-wrapper"">
                                        <input bind=""code"" name=""code"" type=""text"" class=""form-control discount_code"" placeholder=""Nhập mã giảm giá"" value=""  "" id=""checkout_reduction_code"">
                                    </div>
                                    <button bind-event-click=""reduction_code = false, caculateShippingFee(&#39;&#39;)"" class=""btn btn-primary event-voucher-apply"" type=""button"">Áp dụng</button>
                                </div>
                            </div>
                            <div bind-clas");
                WriteLiteral(@"s=""{&#39;warning&#39; : existCode &amp;&amp; !freeShipping &amp;&amp; discount == 0,&#39;success&#39; : existCode &amp;&amp; ( freeShipping || discount &gt;0 )}"" class=""clearfix hide"" bind-show=""code!= null &amp;&amp; code.length &amp;&amp; existCode &amp;&amp; applyWithPromotion"">
                                <div class=""pull-left"">
                                    <i class=""fa fa-check applied-discount-status-success"" aria-hidden=""true""></i>
                                    <i class=""fa fa-exclamation-triangle applied-discount-status-warning"" aria-hidden=""true""></i>
                                </div>
                                <div bind=""code"" class=""pull-left applied-discount-code""></div>
                                <div bind=""(discountShipping &amp;&amp; freeShipping) ? &#39;Miễn phí&#39; : money(discount,&#39;{{amount_no_decimals_with_comma_separator}}₫&#39;)"" class=""pull-right"">0₫</div>
                                <input bind-event-click=""removeCode(&#39;&#39;)"" class=""b");
                WriteLiteral(@"tn btn-delete"" type=""button"" value=""×"" name=""commit"">
                            </div>
                            <div class=""error mt10 hide"" bind-show=""inValidCode"">
                                Mã khuyến mãi không hợp lệ
                            </div>
                            <div class=""error mt10 hide"" bind-show=""!applyWithPromotion &amp;&amp; existCode"">
                                Mã khuyến mãi không được áp dụng chung với chương trình khuyến mãi
                            </div>
                        </div>
                        <hr class=""m0"">
                    </div>
                    <div class=""order-summary order-summary--total-lines"">
                        <div class=""summary-section border-top-none--mobile"">
                            <div class=""total-line total-line-subtotal clearfix"">
                                <span class=""total-line-name pull-left"">
                                    Tạm tính
                                </span>
      ");
                WriteLiteral("                          <span class=\"total-line-subprice pull-right\">\r\n                                    ");
                EndContext();
                BeginContext(15839, 52, false);
#line 322 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                               Write(string.Format(infor, "{0:c0" + "}", @ViewBag._total));

#line default
#line hidden
                EndContext();
                BeginContext(15891, 265, true);
                WriteLiteral(@"
                                </span>
                            </div>
                            <div class=""total-line total-line-shipping clearfix"" bind-show=""requiresShipping"">
                                <span class=""total-line-name pull-left"">
");
                EndContext();
#line 327 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                     if (ViewBag.fee >= 300000)
                                    {
                                        

#line default
#line hidden
                BeginContext(16306, 14, true);
                WriteLiteral("Phí vận chuyển");
                EndContext();
#line 329 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                                   
                                    }
                                    else
                                    {
                                        

#line default
#line hidden
                BeginContext(16495, 6, true);
                WriteLiteral("Có phí");
                EndContext();
#line 333 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                           
                                    }

#line default
#line hidden
                BeginContext(16549, 1004, true);
                WriteLiteral(@"                                </span>
                                <span bind=""shippingFee &gt;  0 ? money(shippingFee,&#39;{{amount_no_decimals_with_comma_separator}}₫&#39;) : ((requiresShipping &amp;&amp; shippingMethods.length == 0) ? &#39;Memoryzone hỗ trợ vận chuyển đơn hàng từ 100.000đ trở lên. Với các sản phẩm có gì trị thấp hơn 100.000đ quý khách vui lòng mua tại showroom.&#39;: &#39;Miễn phí&#39;)""
                                      class=""total-line-shipping pull-right"" bind-show=""ShippingProvinceId || BillingProvinceId &amp;&amp; !otherAddress || (requiresShipping &amp;&amp; shippingMethods.length &gt; 0)"">Miễn phí</span>
                            </div>
                            <div class=""total-line total-line-total clearfix"">
                                <span class=""total-line-name pull-left"">
                                    Tổng cộng
                                </span>
                                <span class=""total-line-price pull-right"">");
                EndContext();
                BeginContext(17554, 52, false);
#line 343 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                                     Write(string.Format(infor, "{0:c0" + "}", @ViewBag._total));

#line default
#line hidden
                EndContext();
                BeginContext(17606, 505, true);
                WriteLiteral(@"</span>
                            </div>
                        </div>
                    </div>
                    <div class=""form-group clearfix hidden-sm hidden-xs"">
                        <div class=""field__input-btn-wrapper mt10"">
                            <a class=""previous-link"" href=""/Cart"">
                                <i class=""fa fa-angle-left fa-lg"" aria-hidden=""true""></i>
                                <span>Quay về giỏ hàng</span>
                            </a>
");
                EndContext();
                BeginContext(18251, 670, true);
                WriteLiteral(@"                            <button class=""btn btn-primary btn-checkout"">ĐẶT HÀNG</button>
                        </div>
                    </div>
                    <div class=""form-group has-error"">
                        <div class=""help-block "">
                            <ul class=""list-unstyled"">
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class=""main"" role=""main"">
                <div class=""main_header"">
                    <div class=""shop logo logo--left "">

                        <a href=""/Home"">
                            ");
                EndContext();
                BeginContext(18921, 134, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "20b76555c63e44eb913e6fefc030deaa", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_11);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_12);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_13);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(19055, 2614, true);
                WriteLiteral(@"
                        </a>

                    </div>
                </div>
                <div class=""main_content"" data-select2-id=""13"">
                    <div class=""row"">
                        <div class=""col-md-6 col-lg-6"">
                            <div class=""section"" id=""add_old"" define=""{billing_address: {&quot;address1&quot;:&quot;Hưng Yên&quot;,&quot;address2&quot;:null,&quot;city&quot;:&quot;TP.Hà Nội&quot;,&quot;company&quot;:null,&quot;country&quot;:&quot;Việt Nam&quot;,&quot;first_name&quot;:&quot;Nguyễn&quot;,&quot;last_name&quot;:&quot;Hòa&quot;,&quot;name&quot;:&quot;Hòa Nguyễn&quot;,&quot;full_name&quot;:&quot;Hòa Nguyễn&quot;,&quot;phone&quot;:&quot;0378491006&quot;,&quot;phone_number&quot;:&quot;0378491006&quot;,&quot;province&quot;:null,&quot;province_code&quot;:null,&quot;district&quot;:null,&quot;district_code&quot;:null,&quot;ward&quot;:null,&quot;ward_code&quot;:null,&quot;zip&quot;:null,&quot;country_code&quot;:&quot;VN&quot;}}"">
                                ");
                WriteLiteral(@"<div class=""section__header"">
                                    <div class=""layout-flex layout-flex--wrap"">
                                        <h2 class=""section__title layout-flex__item layout-flex__item--stretch"">
                                            <i class=""fa fa-id-card-o fa-lg section__title--icon hidden-md hidden-lg"" aria-hidden=""true""></i>
                                            <label class=""control-label"">Thông tin mua hàng</label>
                                        </h2>

                                    </div>
                                </div>
                                <div class=""section__content"">

                                    <div class=""form-group"">
                                        <div class=""field__input-wrapper field__input-wrapper--select"">
                                            <label class=""field__label"" for=""customer-address"">
                                                Địa chỉ mua hàng
                         ");
                WriteLiteral(@"                   </label>
                                            <select class=""field__input field__input--select form-control"" id=""customer_address"" name=""customer_address"" bind-event-change=""billing_address = JSON.parse(this.value),shipping_address= JSON.parse(this.value),changeCustomerAddress(JSON.parse(this.value));"">
                                                <option value=""0"">Địa chỉ mới...</option>

                                                <option selected=""selected"" value=""1"">
                                                    ");
                EndContext();
                BeginContext(21670, 24, false);
#line 399 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                               Write(ViewBag.customer.address);

#line default
#line hidden
                EndContext();
                BeginContext(21694, 2, true);
                WriteLiteral(", ");
                EndContext();
                BeginContext(21697, 21, false);
#line 399 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                                          Write(ViewBag.customer.city);

#line default
#line hidden
                EndContext();
                BeginContext(21718, 212, true);
                WriteLiteral("\r\n                                                </option>\r\n\r\n                                            </select>\r\n                                        </div>\r\n                                    </div>\r\n\r\n");
                EndContext();
                BeginContext(23039, 728, true);
                WriteLiteral(@"

                                    <div class=""form-group"">
                                        <div>
                                            <label class=""field__input-wrapper js-is-filled"" "">
                                                <span class=""field__label"">
                                                    Email
                                                </span>
                                                <input name=""Email"" type=""email"" bind-event-change=""changeEmail()"" bind-event-focus=""handleFocus(this)"" bind-event-blur=""handleFieldBlur(this)"" class=""field__input form-control"" id=""_email"" data-error=""Vui lòng nhập email đúng định dạng"" required="""" readonly=""readonly"" value=""");
                EndContext();
                BeginContext(23768, 22, false);
#line 427 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                                                                                                                                                                                                                                                                                                Write(ViewBag.customer.email);

#line default
#line hidden
                EndContext();
                BeginContext(23790, 33, true);
                WriteLiteral("\" pattern=\"^([a-zA-Z0-9_\\-\\.\\+]+)");
                EndContext();
                BeginContext(23824, 1073, true);
                WriteLiteral(@"@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$"" bind=""email"">
                                            </label>
                                        </div>
                                        <div class=""help-block with-errors"">
                                        </div>
                                    </div>

                                    <div class=""billing"" data-select2-id=""12"">
                                        <div data-select2-id=""11"">
                                            <div class=""form-group"">
                                                <div>
                                                    <label class=""field__input-wrapper js-is-filled"" "">
                                                        <span class=""field__label"">
                                                            Họ và Tên
                                                        </span>
                                     ");
                WriteLiteral("                   <input name=\"name\" type=\"text\"");
                EndContext();
                BeginWriteAttribute("value", " value=\"", 24897, "\"", 24927, 1);
#line 442 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
WriteAttributeValue("", 24905, ViewBag.customer.name, 24905, 22, false);

#line default
#line hidden
                EndWriteAttribute();
                BeginContext(24928, 1125, true);
                WriteLiteral(@" bind-event-change=""saveAbandoned()"" bind-event-focus=""handleFocus(this)"" bind-event-blur=""handleFieldBlur(this)"" class=""field__input form-control"" id=""_billing_address_last_name"" data-error=""Vui lòng nhập họ tên"" required="""" bind=""billing_address.full_name"">
                                                    </label>
                                                </div>
                                                <div class=""help-block with-errors"">
                                                </div>
                                            </div>

                                            <div class=""form-group"">
                                                <div>
                                                    <label class=""field__input-wrapper js-is-filled"" "">
                                                        <span class=""field__label"">
                                                            Số điện thoại
                                                        </s");
                WriteLiteral("pan>\r\n                                                        <input name=\"Phone\" type=\"text\" value=\"");
                EndContext();
                BeginContext(26054, 22, false);
#line 455 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                                                          Write(ViewBag.customer.phone);

#line default
#line hidden
                EndContext();
                BeginContext(26076, 1116, true);
                WriteLiteral(@""" bind-event-change=""saveAbandoned()"" bind-event-focus=""handleFocus(this)"" bind-event-blur=""handleFieldBlur(this)"" class=""field__input form-control"" id=""_billing_address_last_name"" data-error=""Vui lòng nhập họ tên"" required="""" bind=""billing_address.full_name"">
                                                    </label>
                                                </div>
                                                <div class=""help-block with-errors"">
                                                </div>
                                            </div>


                                            <div class=""form-group"">
                                                <div>
                                                    <label class=""field__input-wrapper js-is-filled"" "">
                                                        <span class=""field__label"">
                                                            Địa chỉ
                                                        </span");
                WriteLiteral(">\r\n                                                        <input name=\"Address\" type=\"text\"");
                EndContext();
                BeginWriteAttribute("value", " value=\"", 27192, "\"", 27225, 1);
#line 469 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
WriteAttributeValue("", 27200, ViewBag.customer.address, 27200, 25, false);

#line default
#line hidden
                EndWriteAttribute();
                BeginContext(27226, 1129, true);
                WriteLiteral(@" bind-event-change=""saveAbandoned()"" bind-event-focus=""handleFocus(this)"" bind-event-blur=""handleFieldBlur(this)"" class=""field__input form-control"" id=""_billing_address_last_name"" data-error=""Vui lòng nhập họ tên"" required="""" bind=""billing_address.full_name"">
                                                    </label>
                                                </div>
                                                <div class=""help-block with-errors"">
                                                </div>
                                            </div>



                                            <div class=""form-group"">
                                                <div>
                                                    <label class=""field__input-wrapper js-is-filled"" "">
                                                        <span class=""field__label"">
                                                            Tỉnh/Thành phố
                                                      ");
                WriteLiteral("  </span>\r\n                                                        <input name=\"City\" type=\"text\" value=\"");
                EndContext();
                BeginContext(28356, 21, false);
#line 484 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                                                         Write(ViewBag.customer.city);

#line default
#line hidden
                EndContext();
                BeginContext(28377, 1368, true);
                WriteLiteral(@""" bind-event-change=""saveAbandoned()"" bind-event-focus=""handleFocus(this)"" bind-event-blur=""handleFieldBlur(this)"" class=""field__input form-control"" id=""_billing_address_last_name"" data-error=""Vui lòng nhập họ tên"" required="""" bind=""billing_address.full_name"">
                                                    </label>
                                                </div>
                                                <div class=""help-block with-errors"">
                                                </div>
                                            </div>



                                            <div bind-show=""!otherAddress"" class=""form-group"">
                                                <div class=""error hide"" bind-show=""requiresShipping &amp;&amp; loadedShippingMethods &amp;&amp; shippingMethods.length == 0  &amp;&amp; BillingProvinceId  "">
                                                    <label>Memoryzone hỗ trợ vận chuyển đơn hàng từ 100.000đ trở lên. Với các sản phẩm có gì ");
                WriteLiteral(@"trị thấp hơn 100.000đ quý khách vui lòng mua tại showroom.</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
");
                EndContext();
                BeginContext(48453, 1716, true);
                WriteLiteral(@"                        </div>
                        <div class=""col-md-6 col-lg-6"">
                            <div class=""section shipping-method"" bind-show=""shippingMethodsLoading || shippingMethods.length &gt; 0"">
                                <div class=""section__header"">
                                    <h2 class=""section__title"">
                                        <i class=""fa fa-truck fa-lg section__title--icon hidden-md hidden-lg"" aria-hidden=""true""></i>
                                        <label class=""control-label"">Vận chuyển</label>
                                    </h2>
                                </div>
                                <div class=""section__content"">
                                    <div class=""wait-loading-shipping-methods hide"" bind-show=""shippingMethodsLoading"" style=""margin-bottom:10px"">
                                        <div class=""next-spinner"">
                                            <svg class=""icon-svg icon-svg--color-acce");
                WriteLiteral(@"nt icon-svg--size-32 icon-svg--spinner"">
                                                <use xmlns:xlink=""http://www.w3.org/1999/xlink"" xlink:href=""#next-spinner""></use>
                                            </svg>
                                        </div>
                                    </div>
                                    <div class=""content-box"">
                                        <div class=""content-box__row"">
                                            <div class=""radio-wrapper"">
                                                <div class=""radio__input"">
                                                    <input class=""input-radio"" type=""radio""");
                EndContext();
                BeginWriteAttribute("value", " value=\"", 50169, "\"", 50189, 1);
#line 783 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
WriteAttributeValue("", 50177, ViewBag.fee, 50177, 12, false);

#line default
#line hidden
                EndWriteAttribute();
                BeginContext(50190, 23, true);
                WriteLiteral(" name=\"ShippingMethod\" ");
                EndContext();
#line 783 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                                                                                                        if (ViewBag.fee >= 300000) { 

#line default
#line hidden
                BeginContext(50249, 19, true);
                WriteLiteral(" checked=\"checked\" ");
                EndContext();
#line 783 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
                                                                                                                                                                                                      }

#line default
#line hidden
                BeginContext(50277, 2086, true);
                WriteLiteral(@" fee=""0"">
                                                </div>
                                                <label class=""radio__label"" for=""shipping_method_457189"">
                                                    <span class=""radio__label__primary"">Đơn hàng trên 300.000đ miễn phí ship</span>
                                                    <span class=""radio__label__accessory""><span class=""content-box__emphasis"">Miễn phí</span></span>
                                                </label>
                                            </div>
                                            <!-- /radio-wrapper-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class=""section payment-methods"" bind-class=""{&#39;p0--desktop&#39;: shippingMethods.length == 0}"">
                                <div class=""section__header"">
                         ");
                WriteLiteral(@"           <h2 class=""section__title"">
                                        <i class=""fa fa-credit-card fa-lg section__title--icon hidden-md hidden-lg"" aria-hidden=""true""></i>
                                        <label class=""control-label"">Thanh toán</label>
                                    </h2>
                                </div>
                                <div class=""section__content"">
                                    <div class=""content-box"">

                                        <div class=""content-box__row"">
                                            <div class=""radio-wrapper"">
                                                <div class=""radio__input"">
                                                    <input class=""input-radio"" type=""radio"" value=""Thanh toán khi nhận hàng"" name=""PaymentMethodId"" id=""payment_method_COD"" data-check-id=""3"" bind=""payment_method_id"" checked="""">
                                                </div>
                                     ");
                WriteLiteral("           <label class=\"radio__label\"");
                EndContext();
                BeginWriteAttribute("for", " for=\"", 52363, "\"", 52404, 2);
                WriteAttributeValue("", 52369, "payment_method_", 52369, 15, true);
#line 810 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
WriteAttributeValue("", 52384, ViewBag.customer.id, 52384, 20, false);

#line default
#line hidden
                EndWriteAttribute();
                BeginContext(52405, 2744, true);
                WriteLiteral(@">
                                                    <span class=""radio__label__primary"">Thanh toán khi giao hàng (COD)</span>
                                                    <span class=""radio__label__accessory"">
                                                        <ul>
                                                            <li class=""payment-icon-v2 payment-icon--3"">

                                                                <i class=""fa fa-money payment-icon-fa"" aria-hidden=""true""></i>

                                                            </li>
                                                        </ul>
                                                    </span>
                                                </label>
                                            </div>
                                            <!-- /radio-wrapper-->
                                        </div>

                                        <div class=""radio-wrapper content-box__row ");
                WriteLiteral(@"content-box__row--secondary"" id=""payment-gateway-subfields-COD"" bind-show=""payment_method_id == 391885"">
                                            <div class=""blank-slate"">
                                                <p>
                                                    Bạn sẽ nhận hàng và thanh toán với nhân viên giao hàng.
                                                </p>
                                                <p>
                                                    Lưu ý: MemoryZone hỗ trợ quý khách kiểm tra bao bì và hàng trước khi thanh toán (đồng kiểm).
                                                </p>
                                                <p>
                                                    Nếu có dấu hiệu bất thường xin vui lòng thông báo qua hotline (028) 7301 3878.
                                                </p>
                                                <p>MemoryZone cung cấp dịch vụ hỗ trợ kĩ thuật tại Showroom HCM và Hà Nội cho tất cả các kh");
                WriteLiteral(@"ách hàng đặt mua online.</p>


                                            </div>
                                        </div>


                                        <div class=""content-box__row"">
                                            <div class=""radio-wrapper"">
                                                <div class=""radio__input"">
                                                    <input class=""input-radio"" type=""radio"" value=""Đã thanh toán"" name=""PaymentMethodId"" id=""payment_method_OLN"" data-check-id=""4"" bind=""payment_method_id"">
                                                </div>
                                                <label class=""radio__label""");
                EndContext();
                BeginWriteAttribute("for", " for=\"", 55149, "\"", 55190, 2);
                WriteAttributeValue("", 55155, "payment_method_", 55155, 15, true);
#line 849 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Checkout.cshtml"
WriteAttributeValue("", 55170, ViewBag.customer.id, 55170, 20, false);

#line default
#line hidden
                EndWriteAttribute();
                BeginContext(55191, 5028, true);
                WriteLiteral(@">
                                                    <span class=""radio__label__primary"">Chuyển khoản qua ngân hàng</span>
                                                    <span class=""radio__label__accessory"">
                                                        <ul>
                                                            <li class=""payment-icon-v2 payment-icon--4"">

                                                                <i class=""fa fa-money payment-icon-fa"" aria-hidden=""true""></i>

                                                            </li>
                                                        </ul>
                                                    </span>
                                                </label>
                                            </div>
                                            <!-- /radio-wrapper-->
                                        </div>

                                        <div class=""radio-wrapper content-box__row cont");
                WriteLiteral(@"ent-box__row--secondary hide"" id=""payment-gateway-subfields-ONL"" bind-show=""payment_method_id == 390970"">
                                            <div class=""blank-slate"">
                                                <p>
                                                    *** Trước khi thực hiện chuyển khoản quý khách vui lòng liên hệ hotline: (012) 345 6789 3878 hoặc 037 849 1006 để được hỗ trợ ***
                                                </p>
                                                <p>
                                                    Công Ty TNHH Dịch Vụ Tin Học Siêu Tốc:
                                                </p>
                                                <p>
                                                    Số tài khoản : 123456789
                                                </p>
                                                <p>
                                                    Ngân hàng : Techcombank - chi nhánh Từ Liêm
                      ");
                WriteLiteral(@"                          </p>
                                                <p>- Sau khi chuyển khoản vui lòng báo cho nhân viên (012) 345 6789, để tiến hành xác thực đặt hàng.</p>


                                            </div>
                                        </div>

                                        <script>
                                            document.getElementById(""payment_method_COD"").addEventListener(""change"", function (e) {
                                                if (document.getElementById(""payment_method_COD"").checked) {
                                                    document.getElementById(""payment-gateway-subfields-COD"").setAttribute(""class"", ""radio-wrapper content-box__row content-box__row--secondary"");
                                                    document.getElementById(""payment-gateway-subfields-ONL"").setAttribute(""class"", ""hide"");
                                                }
                                            });

 ");
                WriteLiteral(@"                                           document.getElementById(""payment_method_ONL"").addEventListener(""change"", function (e) {
                                                if (document.getElementById(""payment_method_ONL"").checked) {
                                                    document.getElementById(""payment-gateway-subfields-ONL"").setAttribute(""class"", ""radio-wrapper content-box__row content-box__row--secondary"");
                                                    document.getElementById(""payment-gateway-subfields-COD"").setAttribute(""class"", ""hide"");
                                                }
                                            });
                                        </script>


                                        <a href=""javascript:void(0)"" data-toggle=""modal"" data-target=""#moca-modal"" data-backdrop=""static"" data-keyboard=""false"" class=""trigger-moca-modal"" style=""display: none;"" title=""Thanh toán qua Moca"">
                                        </a>
     ");
                WriteLiteral(@"                                   <a href=""javascript:void(0)"" data-toggle=""modal"" data-target=""#qr-error-modal"" class=""trigger-qr-error-modal"" style=""display: none;"" title=""Lỗi thanh toán"">
                                        </a>
                                        <a data-toggle=""modal"" data-target=""#zalopay_modal"" data-backdrop=""static"" data-keyboard=""false"" class=""trigger-zalopay-modal"" style=""display: none;"" title=""Thanh toán qua ZaloPay"">
                                        </a>
                                        <div class=""modal fade moca-modal"" id=""moca-modal"" tabindex=""-1"" role=""dialog"" style=""opacity: 1; overflow: visible;"">
                                            <div class=""modal-dialog"">
                                                <div class=""modal-content"">
                                                    <div>
                                                        ");
                EndContext();
                BeginContext(60219, 113, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("iframe", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "a5dda44831374a9eb894bc8a056b9bf5", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_15);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_16);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(60332, 2968, true);
                WriteLiteral(@"
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class=""modal fade"" id=""qr-error-modal"" data-width="""" tabindex=""-1"" role=""dialog"">
                                            <div class=""modal-dialog"">
                                                <div class=""modal-content"">
                                                    <div class=""modal-body"">
                                                        <button aria-hidden=""true"" data-dismiss=""modal"" class=""close"" type=""button"">×</button>
                                                        <div class=""invalid_order"">
                                                            <p>Giao dịch của bạn chưa đủ hạn mức thanh toán</p>
                                                            <p>Hạn mức tối thiểu để thanh toán được là <span>");
                WriteLiteral(@"1đ</span></p>
                                                            <p>Vui lòng chọn hình thức thanh toán khác</p>
                                                        </div>
                                                        <div class=""custom_error_message""></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class=""modal fade zalopay_modal"" id=""zalopay_modal"" tabindex=""-1"" role=""dialog"">
                                            <div class=""modal-dialog"">
                                                <div class=""modal-content"">
                                                    <div class=""modal-body"">
                                                        <div style=""display:flex; justify-content: space-around;"">
                                                     ");
                WriteLiteral(@"       <div class=""qr-wrapper"">
                                                                <img>
                                                                <div class=""qr-timer-container"">
                                                                    Thời gian quét mã QR để thanh toán còn <span class=""qr-timer"" style=""color:#4286f6;"">300</span> giây
                                                                </div>
                                                            </div>
                                                            <div class=""qr-guide-content"">
                                                                <p><b>Thực hiện theo hướng dẫn sau để thanh toán:</b></p>
                                                                <p>Bước 1: Mở ứng dụng ZaloPay</p>
                                                                <p>Bước 2: Chọn ""Thanh Toán"" ");
                EndContext();
                BeginContext(63300, 82, false);
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "8abede75528d4cd9945c1a5c6c4a0741", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_17);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_18);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                EndContext();
                BeginContext(63382, 13169, true);
                WriteLiteral(@" và quét mã QR code bên cạnh</p>
                                                                <p>Bước 3: Hoàn thành các bước thanh toán theo hướng dẫn trên ứng dụng</p>
                                                            </div>
                                                        </div>
                                                        <div style=""justify-content: flex-end;display: flex;""><button type=""button"" class=""btn btn-default"" data-dismiss=""modal"">Hủy thanh toán</button></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class=""section hidden-md hidden-lg"">
                                <div class=""form-group clearfix m0"">
                               ");
                WriteLiteral(@"     <input class=""btn btn-primary btn-checkout"" data-loading-text=""Đang xử lý"" type=""submit"" value=""ĐẶT HÀNG"">
                                </div>
                                <div class=""text-center mt20"">
                                    <a class=""previous-link"" href=""/Cart"">
                                        <i class=""fa fa-angle-left fa-lg"" aria-hidden=""true""></i>
                                        <span>Quay về giỏ hàng</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class=""main_footer footer unprint"">



                    <div class=""mt10"">
                        - Từ ngày 22/11/2018 Memoryzone hỗ trợ vận chuyển đơn hàng từ 100.000đ trở lên. Với các sản phẩm có giá trị thấp hơn 100.000đ quý khách vui lòng mua tại showroom.
                        <!-- Jeoway Manager -->
              ");
                WriteLiteral(@"          <!-- <script type=""text/javascript"">
                        var _mtm = _mtm || [];
                                                    _mtm.push({
                            'mtm.startTime': (new Date().getTime()),
                            'event': 'mtm.Start'
                        });
                        var d = document,
                            g = d.createElement('script'),
                            s = d.getElementsByTagName('script')[0];
                                                g.type = 'text/javascript';
                        g.async = true;
                        g.defer = true;
                        g.src = 'https://analytics.jeoway.com/js/container_E5BU680m.js';
                        s.parentNode.insertBefore(g, s);
                    </script> -->
                        <!-- End Jeoway Manager -->
                    </div>
                </div>
                <div class=""modal fade"" id=""refund-policy"" data-width="""" tabindex=""-1"" role=""d");
                WriteLiteral(@"ialog"">
                    <div class=""modal-dialog modal-lg"">
                        <div class=""modal-content"">
                            <div class=""modal-header"">
                                <button aria-hidden=""true"" data-dismiss=""modal"" class=""close"" type=""button"">×</button>
                                <h4 class=""modal-title"">Chính sách hoàn trả</h4>
                            </div>
                            <div class=""modal-body"">
                                <pre></pre>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=""modal fade"" id=""privacy-policy"" data-width="""" tabindex=""-1"" role=""dialog"">
                    <div class=""modal-dialog modal-lg"">
                        <div class=""modal-content"">
                            <div class=""modal-header"">
                                <button aria-hidden=""true"" data-dismiss=""modal"" class=""close"" type=""button"">×</button>
  ");
                WriteLiteral(@"                              <h4 class=""modal-title"">Chính sách bảo mật</h4>
                            </div>
                            <div class=""modal-body"">
                                <pre></pre>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=""modal fade"" id=""terms-of-service"" data-width="""" tabindex=""-1"" role=""dialog"">
                    <div class=""modal-dialog modal-lg"">
                        <div class=""modal-content"">
                            <div class=""modal-header"">
                                <button aria-hidden=""true"" data-dismiss=""modal"" class=""close"" type=""button"">×</button>
                                <h4 class=""modal-title"">Điều khoản sử dụng</h4>
                            </div>
                            <div class=""modal-body"">
                                <pre></pre>
                            </div>
                        </div>
              ");
                WriteLiteral(@"      </div>
                </div>
            </div>
        </div>
    </form>
    <!-- <div id=""icon-symbols"" style=""display: none;"">
        <svg xmlns=""http://www.w3.org/2000/svg"">
           <symbol id=""spinner-large""><svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""-270 364 66 66""><path d=""M-237 428c-17.1 0-31-13.9-31-31s13.9-31 31-31v-2c-18.2 0-33 14.8-33 33s14.8 33 33 33 33-14.8 33-33h-2c0 17.1-13.9 31-31 31z""></path></svg></symbol>
        <symbol id=""chevron-right""><svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 10 10""><path d=""M2 1l1-1 4 4 1 1-1 1-4 4-1-1 4-4""></path></svg></symbol>
        <symbol id=""success""><svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 24 24""><path d=""M12 24C5.373 24 0 18.627 0 12S5.373 0 12 0s12 5.373 12 12-5.373 12-12 12zm0-2c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10zm3.784-13.198c.386-.396 1.02-.404 1.414-.018.396.386.404 1.02.018 1.414l-5.85 6c-.392.403-1.04.403-1.432 0l-3.15-3.23c-.386-.396-.378-1.03.018-1.415.395-.385 1.028-.3");
                WriteLiteral(@"77 1.414.018l2.434 2.5 5.134-5.267z""></path></svg></symbol>
        <symbol id=""arrow""><svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 16 16""><path d=""M16 8.1l-8.1 8.1-1.1-1.1L13 8.9H0V7.3h13L6.8 1.1 7.9 0 16 8.1z""></path></svg></symbol>
        <symbol id=""spinner-button""><svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 20 20""><path d=""M20 10c0 5.523-4.477 10-10 10S0 15.523 0 10 4.477 0 10 0v2c-4.418 0-8 3.582-8 8s3.582 8 8 8 8-3.582 8-8h2z""></path></svg></symbol>
        <symbol id=""next-spinner""><svg preserveAspectRatio=""xMinYMin""><circle class=""next-spinner__ring"" cx=""50%"" cy=""50%"" r=""45%""></circle></svg></symbol>
        </svg>
    </div> -->
    <!-- <script src=""~/Memoryzone-Checkout/jquery-2.1.3.min.js(1).tải xuống"" type=""text/javascript""></script>
    <script src=""~/Memoryzone-Checkout/bootstrap.min.js.tải xuống"" type=""text/javascript""></script>
    <script src=""~/Memoryzone-Checkout/twine.min.js.tải xuống"" type=""text/javascript""></script>
    <script src=""~/Memoryzone-Checkout/vali");
                WriteLiteral(@"dator.min.js.tải xuống"" type=""text/javascript""></script>
    <script src=""~/Memoryzone-Checkout/nprogress.js.tải xuống"" type=""text/javascript""></script>
    <script src=""~/Memoryzone-Checkout/money-helper.js.tải xuống"" type=""text/javascript""></script>
    <script src=""~/Memoryzone-Checkout/select2-full-min.js.tải xuống"" type=""text/javascript""></script>

    <script src=""~/Memoryzone-Checkout/ua-parser.pack.js.tải xuống"" type=""text/javascript""></script>
    <script src=""~/Memoryzone-Checkout/checkout.js.tải xuống"" type=""text/javascript""></script>

    <script type=""text/javascript"">
        $(document).ajaxStart(function() {
            NProgress.start();
        });
        $(document).ajaxComplete(function() {
            NProgress.done();
        });

        context = {}

        $(function() {
            Twine.reset(context).bind().refresh();
        });

        $(document).ready(function() {
            var $select2 = $('.filter-dropdown').select2({
                containerCssC");
                WriteLiteral(@"lass: 'field__input',
                dropdownCssClass: 'field__input',
                dropdownParent: $('.main_content'),
                language: {
                    noResults: function() {
                        return ""Không tìm thấy kết quả""
                    },
                    searching: function() {
                        return ""Đang tìm…""
                    }
                }
            });

            setTimeout(function() {




                Twine.context(document.body).checkout.calculateFeeAndSave('');



            }, 50);

        });
    </script> -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- <script async="""" src=""~/Memoryzone-Checkout/js""></script>

    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-38123902-4');
        gtag('config', 'AW-993120848');
    </script>");
                WriteLiteral(@" -->
    <!-- Google Tag Manager -->
    <!-- <script>
        (function(w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s),
                dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-MCQ622V');
    </script> -->
    <!-- End Google Tag Manager -->
    <!--
    <script type=""text/javascript"">
        $(document).ready(function() {
            $('.hotline-fixed').click(function() {
                _paq.push(['trackGoal', 5]);
            });
        });
    </script>
    <script type=""text/javascript"">
        $(document).ready(function() {

            $('.btn");
                WriteLiteral(@"-checkout').click(function() {

                if ($('#_email').val() !== """") {

                    var emailinput = $('#_email').val();
                    var d = new Date();
                    d.setTime(d.getTime() + (180 * 24 * 60 * 60 * 1000));
                    var expires = ""expires="" + d.toUTCString();
                    document.cookie = 'euser' + ""="" + emailinput + "";"" + expires + "";path=/"";


                    var v_billing_address_last_name = $('#_billing_address_last_name').val();
                    var v_billing_address_phone = $('#_billing_address_phone').val();
                    var v_email = $('#_email').val();
                    var v_billing_address_address1 = $('#_billing_address_address1').val();
                    var vselect2_billingDistrict_container = $('#select2-billingDistrict-container').text();
                    var vselect2_billingProvince_container = $('#select2-billingProvince-container').text();

                    $.post(""https://app2.jeoway.");
                WriteLiteral(@"net/35/add_contact_to_jau.php"", {
                        _billing_address_last_name: v_billing_address_last_name,
                        _billing_address_phone: v_billing_address_phone,
                        _email: v_email,
                        visit_id: visitor_id,
                        _billing_address_address1: v_billing_address_address1,
                        select2_billingDistrict_container: vselect2_billingDistrict_container,
                        select2_billingProvince_container: vselect2_billingProvince_container

                    }, function(data) {
                        if (data == 1) {
                            console.log('send_contact_fine');
                        } else {
                            console.log('error_send_contact_fine');
                        }
                    });

                }


            });

        });
    </script>
    <script type=""text/javascript"">
        $("".btn-checkout"").click(function() {
            va");
                WriteLiteral(@"r checkEmail = $(""#_email"").val();
            var checkName = $(""#_billing_address_last_name"").val();
            var totalDonHang = $("".total-line-price"").text();
            var xoaD = totalDonHang.replace(/\₫/g, '');
            var finalPrice = xoaD.replace(/\./g, '');
            if (checkEmail != '' && checkName != '') {
                _paq.push(['trackGoal', 7, finalPrice]);
                console.log('Send conversion DonHang Fine');
            } else {
                console.log('Error info need');
            }
        })
    </script>
    <script type=""text/javascript"" id="""">
        function getIP(a) {
            dataLayer.push({
                event: ""IpEvent"",
                IpAddress: a.ip
            })
        };
    </script>
    <script type=""text/javascript"" id="""" src=""~/Memoryzone-Checkout/saved_resource""></script> -->
");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_19);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(76558, 11, true);
            WriteLiteral("\r\n\r\n</html>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
