#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4c93245a17722441d8ed3b94c450b1532a4cb51b"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Cart_Index), @"mvc.1.0.view", @"/Views/Cart/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Cart/Index.cshtml", typeof(AspNetCore.Views_Cart_Index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"4c93245a17722441d8ed3b94c450b1532a4cb51b", @"/Views/Cart/Index.cshtml")]
    public class Views_Cart_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("width", new global::Microsoft.AspNetCore.Html.HtmlString("75"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("height", new global::Microsoft.AspNetCore.Html.HtmlString("auto"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
  
    ViewData["Title"] = "Index";
    Layout = "~/Views/_shared/_layoutDanhMuc.cshtml";

#line default
#line hidden
            BeginContext(98, 671, true);
            WriteLiteral(@"
<title>Giỏ hàng</title>

<section class=""bread-crumb"">
    <div class=""container"">
        <div class=""row"">
            <div class=""col-xs-12"">
                <ul class=""breadcrumb"" itemscope="""" itemtype=""http://data-vocabulary.org/Breadcrumb"">
                    <li class=""home"">
                        <a itemprop=""url"" href=""/""><span itemprop=""title"">Trang chủ</span></a>
                        <span><i class=""fa fa-angle-right"" aria-hidden=""true""></i></span>
                    </li>

                    <li><strong itemprop=""title"">Giỏ hàng</strong></li>

                </ul>
            </div>
        </div>
    </div>
</section>

");
            EndContext();
#line 27 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
 if (ViewBag.Count!=0 && ViewBag._cart != null)
{

#line default
#line hidden
            BeginContext(821, 687, true);
            WriteLiteral(@"    <section class=""main-cart-page main-container col1-layout"">
        <div class=""main container hidden-xs"">
            <div class=""header-cart"">
                <div class=""title-cart"">
                    <h1>Giỏ hàng</h1>
                </div>
                <div class=""header-cart title_cart_pc hidden-sm hidden-xs"">

                </div>
            </div>
            <div class=""col-main cart_desktop_page cart-page"">
                <div class=""cart page_cart hidden-xs"">
                    <div class=""app_buyx_msg_cart""></div>
                    <form action=""/Cart/Checkout"" method=""post"" novalidate="""" class=""margin-bottom-0"">
                        ");
            EndContext();
            BeginContext(1509, 23, false);
#line 43 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                   Write(Html.AntiForgeryToken());

#line default
#line hidden
            EndContext();
            BeginContext(1532, 679, true);
            WriteLiteral(@"
                        <div class=""bg-scroll"">
                            <div class=""cart-thead"">
                                <div style=""width: 17%"">Ảnh sản phẩm</div>
                                <div style=""width: 33%""><span class=""nobr"">Tên sản phẩm</span></div>
                                <div style=""width: 15%"" class=""a-center""><span class=""nobr"">Đơn giá</span></div>
                                <div style=""width: 14%"" class=""a-center"">Số lượng</div>
                                <div style=""width: 15%"" class=""a-center"">Thành tiền</div>
                                <div style=""width: 6%"">Xoá</div>
                            </div>
");
            EndContext();
#line 53 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                             foreach (var item in ViewBag._cart)
                            {
                                

#line default
#line hidden
            BeginContext(2398, 98, true);
            WriteLiteral("                                <div class=\"cart-tbody\">\r\n                                    <div");
            EndContext();
            BeginWriteAttribute("class", " class=\"", 2496, "\"", 2542, 3);
            WriteAttributeValue("", 2504, "item-cart", 2504, 9, true);
            WriteAttributeValue(" ", 2513, "productid-", 2514, 11, true);
#line 58 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 2524, item.ItemsList.id, 2524, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(2543, 151, true);
            WriteLiteral(">\r\n                                        <div style=\"width: 17%\" class=\"image\">\r\n                                            <a class=\"product-image\"");
            EndContext();
            BeginWriteAttribute("title", " title=\"", 2694, "\"", 2722, 1);
#line 60 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 2702, item.ItemsList.name, 2702, 20, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginWriteAttribute("href", " href=\"", 2723, "\"", 2764, 2);
            WriteAttributeValue("", 2730, "/Product/Detail/", 2730, 16, true);
#line 60 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 2746, item.ItemsList.id, 2746, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(2765, 51, true);
            WriteLiteral(">\r\n                                                ");
            EndContext();
            BeginContext(2816, 103, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "b8240310619842dd924e6de512709ec5", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "alt", 1, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
#line 61 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
AddHtmlAttributeValue("", 2851, item.ItemsList.name, 2851, 20, false);

#line default
#line hidden
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            AddHtmlAttributeValue("", 2878, "~/Upload/Products/", 2878, 18, true);
#line 61 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
AddHtmlAttributeValue("", 2896, item.ItemsList.media, 2896, 21, false);

#line default
#line hidden
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(2919, 281, true);
            WriteLiteral(@"
                                            </a>
                                        </div>
                                        <div style=""width: 33%"" class=""a-center prd_name"">
                                            <h2 class=""product-name""><a class=""text2line""");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 3200, "\"", 3241, 2);
            WriteAttributeValue("", 3207, "/Product/Detail/", 3207, 16, true);
#line 65 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 3223, item.ItemsList.id, 3223, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(3242, 1, true);
            WriteLiteral(">");
            EndContext();
            BeginContext(3244, 19, false);
#line 65 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                                                               Write(item.ItemsList.name);

#line default
#line hidden
            EndContext();
            BeginContext(3263, 439, true);
            WriteLiteral(@"</a></h2>
                                            <span class=""variant-title"" style=""display: none;""></span>
                                        </div>
                                        <div style=""width: 15%"" class=""a-center"">
                                            <span class=""item-price"">
                                                <span class=""price"">
                                                    ");
            EndContext();
            BeginContext(3703, 52, false);
#line 71 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                               Write(string.Format("{0:0,00.00} ₫", item.ItemsList.price));

#line default
#line hidden
            EndContext();
            BeginContext(3755, 418, true);
            WriteLiteral(@"
                                                </span>
                                            </span>
                                        </div>
                                        <div style=""width: 14%"" class=""a-center"">
                                            <div class=""input_qty_pr"">
                                                <input class=""variantID"" type=""hidden"" name=""variantId""");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 4173, "\"", 4199, 1);
#line 77 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4181, item.ItemsList.id, 4181, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(4200, 58, true);
            WriteLiteral(">\r\n                                                <button");
            EndContext();
            BeginWriteAttribute("id", " id=\"", 4258, "\"", 4286, 2);
            WriteAttributeValue("", 4263, "down_", 4263, 5, true);
#line 78 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4268, item.ItemsList.id, 4268, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginWriteAttribute("onclick", " onclick=\"", 4287, "\"", 4513, 22);
            WriteAttributeValue("", 4297, "var", 4297, 3, true);
            WriteAttributeValue(" ", 4300, "result", 4301, 7, true);
            WriteAttributeValue(" ", 4307, "=", 4308, 2, true);
            WriteAttributeValue(" ", 4309, "document.getElementById(\'qtyItem_", 4310, 34, true);
#line 78 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4343, item.ItemsList.id, 4343, 18, false);

#line default
#line hidden
            WriteAttributeValue("", 4361, "\');", 4361, 3, true);
            WriteAttributeValue(" ", 4364, "var", 4365, 4, true);
            WriteAttributeValue(" ", 4368, "qtyItem_", 4369, 9, true);
#line 78 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4377, item.ItemsList.id, 4377, 18, false);

#line default
#line hidden
            WriteAttributeValue("", 4395, "=result.value;", 4395, 14, true);
            WriteAttributeValue(" ", 4409, "if", 4410, 3, true);
            WriteAttributeValue(" ", 4412, "(!isNaN(qtyItem_", 4413, 17, true);
#line 78 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4429, item.ItemsList.id, 4429, 18, false);

#line default
#line hidden
            WriteAttributeValue("", 4447, ")", 4447, 1, true);
            WriteAttributeValue(" ", 4448, "&&", 4449, 3, true);
            WriteAttributeValue(" ", 4451, "qtyItem_", 4452, 9, true);
#line 78 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4460, item.ItemsList.id, 4460, 18, false);

#line default
#line hidden
            WriteAttributeValue(" ", 4478, ">", 4479, 2, true);
            WriteAttributeValue(" ", 4480, "1)", 4481, 3, true);
            WriteAttributeValue(" ", 4483, "result.value--;", 4484, 16, true);
            WriteAttributeValue(" ", 4499, "return", 4500, 7, true);
            WriteAttributeValue(" ", 4506, "false;", 4507, 7, true);
            EndWriteAttribute();
            BeginContext(4514, 68, true);
            WriteLiteral(" class=\"reduced_pop items-count btn-minus\" type=\"button\">-</button> ");
            EndContext();
            BeginContext(4597, 91, true);
            WriteLiteral("\r\n                                                <input type=\"text\" maxlength=\"12\" min=\"1\"");
            EndContext();
            BeginWriteAttribute("class", " class=\"", 4688, "\"", 4768, 6);
            WriteAttributeValue("", 4696, "input-text", 4696, 10, true);
            WriteAttributeValue(" ", 4706, "number-sidebar", 4707, 15, true);
            WriteAttributeValue(" ", 4721, "input_pop", 4722, 10, true);
            WriteAttributeValue(" ", 4731, "input_pop", 4732, 10, true);
            WriteAttributeValue(" ", 4741, "qtyItem_", 4742, 9, true);
#line 79 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4750, item.ItemsList.id, 4750, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginWriteAttribute("id", " id=\"", 4769, "\"", 4800, 2);
            WriteAttributeValue("", 4774, "qtyItem_", 4774, 8, true);
#line 79 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4782, item.ItemsList.id, 4782, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(4801, 22, true);
            WriteLiteral(" name=\"Lines\" size=\"4\"");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 4823, "\"", 4845, 1);
#line 79 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4831, item.quantity, 4831, 14, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(4846, 58, true);
            WriteLiteral(">\r\n                                                <button");
            EndContext();
            BeginWriteAttribute("id", " id=\"", 4904, "\"", 4930, 2);
            WriteAttributeValue("", 4909, "up_", 4909, 3, true);
#line 80 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4912, item.ItemsList.id, 4912, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginWriteAttribute("onclick", " onclick=\"", 4931, "\"", 5123, 17);
            WriteAttributeValue("", 4941, "var", 4941, 3, true);
            WriteAttributeValue(" ", 4944, "result", 4945, 7, true);
            WriteAttributeValue(" ", 4951, "=", 4952, 2, true);
            WriteAttributeValue(" ", 4953, "document.getElementById(\'qtyItem_", 4954, 34, true);
#line 80 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 4987, item.ItemsList.id, 4987, 18, false);

#line default
#line hidden
            WriteAttributeValue("", 5005, "\');", 5005, 3, true);
            WriteAttributeValue(" ", 5008, "var", 5009, 4, true);
            WriteAttributeValue(" ", 5012, "qtyItem_", 5013, 9, true);
#line 80 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 5021, item.ItemsList.id, 5021, 18, false);

#line default
#line hidden
            WriteAttributeValue("", 5039, "=result.value;", 5039, 14, true);
            WriteAttributeValue(" ", 5053, "if", 5054, 3, true);
            WriteAttributeValue(" ", 5056, "(!isNaN(qtyItem_", 5057, 17, true);
#line 80 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 5073, item.ItemsList.id, 5073, 18, false);

#line default
#line hidden
            WriteAttributeValue("", 5091, "))", 5091, 2, true);
            WriteAttributeValue(" ", 5093, "result.value++;", 5094, 16, true);
            WriteAttributeValue(" ", 5109, "return", 5110, 7, true);
            WriteAttributeValue(" ", 5116, "false;", 5117, 7, true);
            EndWriteAttribute();
            BeginContext(5124, 390, true);
            WriteLiteral(@" class=""increase_pop items-count btn-plus"" type=""button"">+</button>
                                            </div>
                                        </div>
                                        <div style=""width: 15%"" class=""a-center"">
                                            <span class=""cart-price"">
                                                <span class=""price""");
            EndContext();
            BeginWriteAttribute("id", " id=\"", 5514, "\"", 5543, 2);
            WriteAttributeValue("", 5519, "price_", 5519, 6, true);
#line 85 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 5525, item.ItemsList.id, 5525, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(5544, 55, true);
            WriteLiteral(">\r\n                                                    ");
            EndContext();
            BeginContext(5600, 66, false);
#line 86 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                               Write(string.Format("{0:0,00.00} ₫", item.ItemsList.price*item.quantity));

#line default
#line hidden
            EndContext();
            BeginContext(5666, 148, true);
            WriteLiteral("\r\n                                                    <script>\r\n                                                        document.getElementById(\'up_");
            EndContext();
            BeginContext(5815, 17, false);
#line 88 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                               Write(item.ItemsList.id);

#line default
#line hidden
            EndContext();
            BeginContext(5832, 159, true);
            WriteLiteral("\').addEventListener(\'click\', function () {\r\n                                                            var result = parseInt(document.getElementById(\'qtyItem_");
            EndContext();
            BeginContext(5992, 17, false);
#line 89 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                                              Write(item.ItemsList.id);

#line default
#line hidden
            EndContext();
            BeginContext(6009, 165, true);
            WriteLiteral("\').value);\r\n                                                            \r\n                                                            document.getElementById(\'price_");
            EndContext();
            BeginContext(6175, 17, false);
#line 91 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                      Write(item.ItemsList.id);

#line default
#line hidden
            EndContext();
            BeginContext(6192, 15, true);
            WriteLiteral("\').innerHTML =(");
            EndContext();
            BeginContext(6208, 20, false);
#line 91 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                                                       Write(item.ItemsList.price);

#line default
#line hidden
            EndContext();
            BeginContext(6228, 210, true);
            WriteLiteral("* result).toFixed(2).replace(/\\d(?=(\\d{3})+\\.)/g, \'$&,\')+\" ₫\";\r\n                                                        })\r\n                                                        document.getElementById(\'down_");
            EndContext();
            BeginContext(6439, 17, false);
#line 93 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                 Write(item.ItemsList.id);

#line default
#line hidden
            EndContext();
            BeginContext(6456, 159, true);
            WriteLiteral("\').addEventListener(\'click\', function () {\r\n                                                            var result = parseInt(document.getElementById(\'qtyItem_");
            EndContext();
            BeginContext(6616, 17, false);
#line 94 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                                              Write(item.ItemsList.id);

#line default
#line hidden
            EndContext();
            BeginContext(6633, 187, true);
            WriteLiteral("\').value);\r\n                                                            if (result == 1) {\r\n                                                                document.getElementById(\'price_");
            EndContext();
            BeginContext(6821, 17, false);
#line 96 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                          Write(item.ItemsList.id);

#line default
#line hidden
            EndContext();
            BeginContext(6838, 15, true);
            WriteLiteral("\').innerHTML =(");
            EndContext();
            BeginContext(6854, 20, false);
#line 96 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                                                           Write(item.ItemsList.price);

#line default
#line hidden
            EndContext();
            BeginContext(6874, 282, true);
            WriteLiteral(@").toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,')+"" ₫"";
                                                            }
                                                            else {
                                                                document.getElementById('price_");
            EndContext();
            BeginContext(7157, 17, false);
#line 99 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                          Write(item.ItemsList.id);

#line default
#line hidden
            EndContext();
            BeginContext(7174, 14, true);
            WriteLiteral("\').innerHTML=(");
            EndContext();
            BeginContext(7189, 20, false);
#line 99 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                                                          Write(item.ItemsList.price);

#line default
#line hidden
            EndContext();
            BeginContext(7209, 9, true);
            WriteLiteral("* result-");
            EndContext();
            BeginContext(7219, 20, false);
#line 99 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                                                                                        Write(item.ItemsList.price);

#line default
#line hidden
            EndContext();
            BeginContext(7239, 525, true);
            WriteLiteral(@").toFixed(1).replace(/\d(?=(\d{3})+\.)/g, '$&,')+"" ₫"";
                                                            }
                                                        })
                                                    </script>
                                                </span>
                                            </span>
                                        </div><div style=""width: 6%"">
                                            <a class=""button remove-item remove-item-cart"" title=""Xóa""");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 7764, "\"", 7802, 2);
            WriteAttributeValue("", 7771, "/Cart/Remove/", 7771, 13, true);
#line 106 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
WriteAttributeValue("", 7784, item.ItemsList.id, 7784, 18, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(7803, 10, true);
            WriteLiteral(" data-id=\"");
            EndContext();
            BeginContext(7814, 17, false);
#line 106 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                                                                                                                  Write(item.ItemsList.id);

#line default
#line hidden
            EndContext();
            BeginContext(7831, 295, true);
            WriteLiteral(@""">
                                                <span><i class=""fa fa-times"" aria-hidden=""true""></i></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
");
            EndContext();
#line 112 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                            }

#line default
#line hidden
            BeginContext(8157, 977, true);
            WriteLiteral(@"                        </div>
                    </form>
                    <div class=""cart-collaterals cart_submit row"">
                        <div class=""totals col-sm-12 col-md-12 col-xs-12"">
                            <div class=""totals"">
                                <div class=""inner"">
                                    <table class=""table shopping-cart-table-total margin-bottom-0"" id=""shopping-cart-totals-table"">
                                        <colgroup><col><col></colgroup>
                                        <tfoot>
                                            <tr>
                                                <td colspan=""19"" class=""a-right""><span>Tổng tiền:</span></td>
                                                <td colspan=""2"" class=""a-right"">
                                                    <strong>
                                                        <span class=""totals_price price"" id=""totals_price"">
");
            EndContext();
#line 127 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                              
                                                                double totals = 0;
                                                                foreach (var item in ViewBag._cart)
                                                                {
                                                                    totals += item.quantity * item.ItemsList.price;
                                                                }
                                                                

#line default
#line hidden
            BeginContext(9699, 38, false);
#line 133 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                                                           Write(string.Format("{0:0,00.00} ₫", totals));

#line default
#line hidden
            EndContext();
            BeginContext(9802, 60, true);
            WriteLiteral("                                                            ");
            EndContext();
            BeginContext(10288, 1220, true);
            WriteLiteral(@"
                                                        </span>
                                                    </strong>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                    <ul class=""checkout"">
                                        <li class=""clearfix f-right"">
                                            <button class=""btn btn-white f-left"" title=""Tiếp tục mua hàng"" type=""button"" onclick=""window.location.href='/Home'""><span>Tiếp tục mua hàng</span></button>
                                            <button class=""btn btn-primary button btn-proceed-checkout f-right"" title=""Thực hiện thanh toán"" type=""button"" onclick=""window.location.href='/Cart/Checkout'""><span>Thực hiện thanh toán</span></button>

                                        </li>

                                    </ul>

                  ");
            WriteLiteral("              </div>\r\n\r\n                            </div>\r\n\r\n                        </div>\r\n\r\n                    </div>\r\n\r\n                </div>\r\n\r\n            </div>\r\n\r\n\r\n        </div>\r\n\r\n\r\n");
            EndContext();
            BeginContext(15280, 16, true);
            WriteLiteral("    </section>\r\n");
            EndContext();
#line 236 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
                   
}
else
{

#line default
#line hidden
            BeginContext(15721, 788, true);
            WriteLiteral(@"    <section class=""main-cart-page main-container col1-layout"">
        <div class=""main container hidden-xs"">
            <div class=""header-cart"">
                <div class=""title-cart"">
                    <h1>Giỏ hàng</h1>
                </div>
                <div class=""header-cart title_cart_pc hidden-sm hidden-xs""><p class=""hidden-xs-down"">Không có sản phẩm nào. Quay lại <a href=""/"" style=""color:;"">cửa hàng</a> để tiếp tục mua sắm.</p></div>
            </div>
            <div class=""col-main cart_desktop_page cart-page""></div>
        </div>
        <div class=""cart-mobile hidden-md hidden-lg hidden-sm"">
            <div class=""app_buyx_msg_cart""></div>
            <form action=""/cart"" method=""post"" novalidate="""" class=""margin-bottom-0"">
                ");
            EndContext();
            BeginContext(16510, 23, false);
#line 253 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
           Write(Html.AntiForgeryToken());

#line default
#line hidden
            EndContext();
            BeginContext(16533, 304, true);
            WriteLiteral(@"
                <div class=""header-cart"" style=""background:#fff;"">

                    <div class=""title-cart title_cart_mobile"">
                        <h3>Giỏ hàng của bạn</h3>
                    </div>

                </div>



            </form>

        </div>

    </section>
");
            EndContext();
#line 269 "G:\ASP.NET\project_banhang\project_banhang\Views\Cart\Index.cshtml"
}

#line default
#line hidden
            BeginContext(16840, 2, true);
            WriteLiteral("\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
