#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "10ffc5eaa91f7d135a320584ecf041af91715876"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Account_Index), @"mvc.1.0.view", @"/Views/Account/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Account/Index.cshtml", typeof(AspNetCore.Views_Account_Index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 7 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
using Microsoft.AspNetCore.Http;

#line default
#line hidden
#line 8 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
using project_banhang.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"10ffc5eaa91f7d135a320584ecf041af91715876", @"/Views/Account/Index.cshtml")]
    public class Views_Account_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 1 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
  
    ViewData["Title"] = "Index";
    Layout = "~/Views/_shared/_chiTiet.cshtml";

#line default
#line hidden
            BeginContext(90, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(211, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 11 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
 if (Context.Session.GetString("customer_email") != null || Context.Session.GetString("customer_email") != " ")
{

#line default
#line hidden
            BeginContext(385, 1324, true);
            WriteLiteral(@"    <section class=""bread-crumb"">
        <div class=""container"">
            <div class=""row"">
                <div class=""col-xs-12"">
                    <ul class=""breadcrumb"" itemscope="""" itemtype=""http://data-vocabulary.org/Breadcrumb"">
                        <li class=""home"">
                            <a itemprop=""url"" href=""/Home/""><span itemprop=""title"">Trang chủ</span></a>
                            <span><i class=""fa fa-angle-right"" aria-hidden=""true""></i></span>
                        </li>

                        <li><strong itemprop=""title"">Trang khách hàng</strong></li>

                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class=""signup page_customer_account"">
        <div class=""container"">
            <div class=""row"">
                <div class=""col-xs-12 col-sm-12 col-md-12 col-main-acount"">
                    <div id=""parent"" class=""row"">
                        <div id=""a"" class=""col-xs-12 col-sm-12 col-");
            WriteLiteral(@"lg-9 col-left-account"">
                            <div class=""page-title m992"">
                                <h1 class=""title-head margin-top-0""><a href=""#"">Trang khách hàng</a></h1>
                            </div>
                            <div class=""form-signup name-account m992"">
");
            EndContext();
#line 40 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                  
                                    DataContext db = new DataContext();
                                    var users = db.customers.OrderByDescending(tbl => tbl.id).ToList();
                                

#line default
#line hidden
            BeginContext(1958, 187, true);
            WriteLiteral("                                <p>\r\n                                    <strong>\r\n                                        Xin chào, <a href=\"/account/addresses\" style=\"color:#008744;\">\r\n");
            EndContext();
#line 47 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                              
                                                if (Context.Session.GetString("customer_email") != null)
                                                {
                                                    foreach (var item in users)
                                                    {
                                                        if (Context.Session.GetString("customer_email") == item.email)
                                                        {
                                                            

#line default
#line hidden
            BeginContext(2726, 9, false);
#line 54 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                       Write(item.name);

#line default
#line hidden
            EndContext();
#line 54 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                      
                                                        }
                                                    }
                                                }

                                            

#line default
#line hidden
            BeginContext(2951, 1428, true);
            WriteLiteral(@"                                        </a>&nbsp;!
                                    </strong>
                                </p>
                            </div>
                            <div class=""col-xs-12 col-sm-12 col-lg-12 no-padding"">

                                <div class=""my-account"">
                                    <div class=""dashboard"">

                                        <div class=""recent-orders"">
                                            <div class=""table-responsive tab-all"" style=""overflow-x:auto;"">
                                                <table class=""table table-cart"" id=""my-orders-table"">
                                                    <thead class=""thead-default"">
                                                        <tr>
                                                            <th>Đơn hàng</th>
                                                            <th>Ngày</th>

                                                            <");
            WriteLiteral(@"th>Địa chỉ</th>
                                                            <th>Giá trị đơn hàng</th>
                                                            <th>Tình trạng thanh toán</th>
                                                            <th>Trạng thái</th>
                                                        </tr>
                                                    </thead>

");
            EndContext();
#line 91 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                     foreach (var item in Model)
                                                    {

#line default
#line hidden
            BeginContext(4900, 218, true);
            WriteLiteral("                                                        <thead class=\"card-body\">\r\n                                                            <tr>\r\n                                                                <th>#");
            EndContext();
            BeginContext(5119, 7, false);
#line 95 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                Write(item.id);

#line default
#line hidden
            EndContext();
            BeginContext(5126, 78, true);
            WriteLiteral(" HL</th>\r\n                                                                <th>");
            EndContext();
            BeginContext(5205, 12, false);
#line 96 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                               Write(item.created);

#line default
#line hidden
            EndContext();
            BeginContext(5217, 75, true);
            WriteLiteral("</th>\r\n                                                                <th>");
            EndContext();
            BeginContext(5293, 12, false);
#line 97 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                               Write(item.address);

#line default
#line hidden
            EndContext();
            BeginContext(5305, 7, true);
            WriteLiteral("</th>\r\n");
            EndContext();
#line 98 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                  
                                                                    var infor = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
                                                                

#line default
#line hidden
            BeginContext(5586, 68, true);
            WriteLiteral("                                                                <th>");
            EndContext();
            BeginContext(5655, 47, false);
#line 101 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                               Write(string.Format(infor, "{0:c0" + "}", item.price));

#line default
#line hidden
            EndContext();
            BeginContext(5702, 75, true);
            WriteLiteral("</th>\r\n                                                                <th>");
            EndContext();
            BeginContext(5778, 19, false);
#line 102 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                               Write(item.status_payment);

#line default
#line hidden
            EndContext();
            BeginContext(5797, 77, true);
            WriteLiteral("</th>\r\n                                                                <th>\r\n");
            EndContext();
#line 104 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                     if (item.status == false)
                                                                    {
                                                                        

#line default
#line hidden
            BeginContext(6119, 14, true);
            WriteLiteral("Đang giao hàng");
            EndContext();
#line 106 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                                                   
                                                                    }
                                                                    else
                                                                    {
                                                                        

#line default
#line hidden
            BeginContext(6436, 12, true);
            WriteLiteral("Đã nhận hàng");
            EndContext();
#line 110 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                                                 
                                                                    }

#line default
#line hidden
            BeginContext(6528, 204, true);
            WriteLiteral("                                                                </th>\r\n                                                            </tr>\r\n                                                        </thead>\r\n");
            EndContext();
#line 115 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                    }

#line default
#line hidden
            BeginContext(6787, 861, true);
            WriteLiteral(@"

                                                </table>

                                            </div>

                                            <div class=""paginate-pages pull-right page-account text-right col-xs-12 col-sm-12 col-md-12 col-lg-12"">

                                            </div>
                                        </div>
                                    </div>

                                </div>

                            </div>
                        </div>
                        <div id=""b"" class=""col-xs-12 col-sm-12 col-lg-3 col-right-account margin-top-20"">
                            <div class=""block-account"">
                                <div class=""block-title-account""><h5>Tài khoản của tôi</h5></div>
                                <div class=""block-content form-signup"">
");
            EndContext();
#line 136 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                     foreach (var item in users)
                                    {
                                        if (item.id == ViewBag.user)
                                        {

#line default
#line hidden
            BeginContext(7866, 131, true);
            WriteLiteral("                                            <p><i class=\"fa fa-mobile font-some\" aria-hidden=\"true\"></i> <span>Điện thoại: </span> ");
            EndContext();
            BeginContext(7998, 10, false);
#line 140 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                                                                              Write(item.phone);

#line default
#line hidden
            EndContext();
            BeginContext(8008, 131, true);
            WriteLiteral("</p>\r\n                                            <p><i class=\"fa fa-map-marker font-some\" aria-hidden=\"true\"></i> <span> Địa chỉ: ");
            EndContext();
            BeginContext(8140, 12, false);
#line 141 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                                                                        Write(item.address);

#line default
#line hidden
            EndContext();
            BeginContext(8152, 13, true);
            WriteLiteral("</span></p>\r\n");
            EndContext();
            BeginContext(8167, 122, true);
            WriteLiteral("                                            <p><i class=\"fa fa-plane font-some\" aria-hidden=\"true\"></i> <span> Thành phố: ");
            EndContext();
            BeginContext(8290, 9, false);
#line 143 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                                                                     Write(item.city);

#line default
#line hidden
            EndContext();
            BeginContext(8299, 134, true);
            WriteLiteral("</span></p>\r\n                                            <p><i class=\"fa fa-plane font-some\" aria-hidden=\"true\"></i> <span> Quốc gia: ");
            EndContext();
            BeginContext(8434, 12, false);
#line 144 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                                                                                                                    Write(item.country);

#line default
#line hidden
            EndContext();
            BeginContext(8446, 13, true);
            WriteLiteral("</span></p>\r\n");
            EndContext();
#line 145 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"

                                        }
                                    }

#line default
#line hidden
            BeginContext(8543, 36, true);
            WriteLiteral("                                    ");
            EndContext();
            BeginContext(9150, 364, true);
            WriteLiteral(@"

                                    <p style=""margin-top:20px;""><a href=""/Account/Addresses"" class=""btn btn-full btn-primary"">Sổ địa chỉ</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
");
            EndContext();
#line 164 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
}



else
    {

#line default
#line hidden
            BeginContext(9536, 771, true);
            WriteLiteral(@"        <section class=""bread-crumb"">
            <div class=""container"">
                <div class=""row"">
                    <div class=""col-xs-12"">
                        <ul class=""breadcrumb"" itemscope="""" itemtype=""http://data-vocabulary.org/Breadcrumb"">
                            <li class=""home"">
                                <a itemprop=""url"" href=""/""><span itemprop=""title"">Trang chủ</span></a>
                                <span><i class=""fa fa-angle-right"" aria-hidden=""true""></i></span>
                            </li>

                            <li><strong itemprop=""title"">Đăng nhập tài khoản</strong></li>

                        </ul>
                    </div>
                </div>
            </div>
        </section>
");
            EndContext();
            BeginContext(10309, 586, true);
            WriteLiteral(@"        <div class=""container margin-bottom-20"">
            <h1 class=""title-head""><span>Đăng nhập tài khoản</span></h1>
            <div class=""row"">
                <div class=""col-lg-6"">
                    <div class=""page-login"">
                        <div id=""login"">
                            <span>
                                Nếu bạn đã có tài khoản, đăng nhập tại đây.
                            </span>
                            <form accept-charset=""UTF-8"" action=""/Account/LoginPost"" id=""customer_login"" method=""post"">
                                ");
            EndContext();
            BeginContext(10896, 23, false);
#line 198 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"
                           Write(Html.AntiForgeryToken());

#line default
#line hidden
            EndContext();
            BeginContext(10919, 565, true);
            WriteLiteral(@"
                                <input name=""FormType"" type=""hidden"" value=""customer_login"">
                                <input name=""utf8"" type=""hidden"" value=""true"">
                                <div class=""form-signup"">

                                </div>
                                <div class=""form-signup clearfix"">
                                    <fieldset class=""form-group"">
                                        <label>Email <span class=""required"">*</span></label>
                                        <input type=""email""");
            EndContext();
            BeginWriteAttribute("pattern", " pattern=\"", 11484, "\"", 11535, 3);
            WriteAttributeValue("", 11494, "[a-z0-9._%+-]+", 11494, 14, true);
            WriteAttributeValue("", 11508, "@", 11508, 1, true);
            WriteAttributeValue("", 11510, "[a-z0-9.-]+\\.[a-z]{2,63}$", 11510, 25, true);
            EndWriteAttribute();
            BeginContext(11536, 2470, true);
            WriteLiteral(@" class=""form-control form-control-lg"" value="""" name=""email"" id=""customer_email"" placeholder=""Email"" required="""">
                                    </fieldset>
                                    <fieldset class=""form-group"">
                                        <label>Mật khẩu <span class=""required"">*</span></label>
                                        <input type=""password"" class=""form-control form-control-lg"" value="""" name=""password"" id=""customer_password"" placeholder=""Mật khẩu"" required="""">
                                    </fieldset>



                                    <div class=""pull-xs-left"" style=""margin-top: 25px;"">
                                        <input class=""btn btn-style btn-primary"" type=""submit"" value=""Đăng nhập"">
                                        <a href=""/Account/Register"" class=""btn-link-style btn-register"" style=""margin-left: 20px;text-decoration: underline; "">Đăng ký</a>
                                    </div>
                                </di");
            WriteLiteral(@"v>
                            </form>

                            <div style=""margin-top: 5px;"" id=""social_login_widget""><div id=""social_login"" style=""width: 280px; height: 120px;""><iframe id=""sa_iframe"" width=""280"" height=""120"" style=""border:none;"" src=""https://sociallogin.sapoapps.vn/sociallogin/block_login?store=memoryzone-com-vn.mysapo.net""></iframe></div></div>
                        </div>


                    </div>
                </div>
                <div class=""col-lg-6 h_recover"">

                    <div id=""recover-password"" class=""form-signup page-login"">
                        <span>
                            Bạn quên mật khẩu? Nhập địa chỉ email để lấy lại mật khẩu qua email.
                        </span>
                        <form accept-charset=""UTF-8"" action=""/account/recover"" id=""recover_customer_password"" method=""post"">
                            <input name=""FormType"" type=""hidden"" value=""recover_customer_password"">
                            <input name");
            WriteLiteral(@"=""utf8"" type=""hidden"" value=""true"">
                            <div class=""form-signup"" style=""color: red;"">

                            </div>
                            <div class=""form-signup clearfix"">
                                <fieldset class=""form-group"">
                                    <label>Email <span class=""required"">*</span></label>
                                    <input type=""email""");
            EndContext();
            BeginWriteAttribute("pattern", " pattern=\"", 14006, "\"", 14057, 3);
            WriteAttributeValue("", 14016, "[a-z0-9._%+-]+", 14016, 14, true);
            WriteAttributeValue("", 14030, "@", 14030, 1, true);
            WriteAttributeValue("", 14032, "[a-z0-9.-]+\\.[a-z]{2,63}$", 14032, 25, true);
            EndWriteAttribute();
            BeginContext(14058, 550, true);
            WriteLiteral(@" class=""form-control form-control-lg"" value="""" name=""Email"" id=""recover-email"" placeholder=""Email"" required="""">
                                </fieldset>
                            </div>
                            <div class=""action_bottom"">
                                <input class=""btn btn-style btn-primary"" style=""margin-top: 28px;"" type=""submit"" value=""Lấy lại mật khẩu"">

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
");
            EndContext();
#line 256 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Index.cshtml"

}

#line default
#line hidden
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
