#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Login.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c66d4d44aa5321adad0059a195da1703ec0ff16c"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Account_Login), @"mvc.1.0.view", @"/Views/Account/Login.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Account/Login.cshtml", typeof(AspNetCore.Views_Account_Login))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"c66d4d44aa5321adad0059a195da1703ec0ff16c", @"/Views/Account/Login.cshtml")]
    public class Views_Account_Login : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Login.cshtml"
  
    ViewData["Title"] = "Login";
    Layout = "~/Views/_shared/_chiTiet.cshtml";

#line default
#line hidden
            BeginContext(92, 1153, true);
            WriteLiteral(@"
<section class=""bread-crumb"">
    <div class=""container"">
        <div class=""row"">
            <div class=""col-xs-12"">
                <ul class=""breadcrumb"" itemscope="""" itemtype=""http://data-vocabulary.org/Breadcrumb"">
                    <li class=""home"">
                        <a itemprop=""url"" href=""/""><span itemprop=""title"">Trang chủ</span></a>
                        <span><i class=""fa fa-angle-right"" aria-hidden=""true""></i></span>
                    </li>

                    <li><strong itemprop=""title"">Đăng nhập tài khoản</strong></li>

                </ul>
            </div>
        </div>
    </div>
</section>

<div class=""container margin-bottom-20"">
    <h1 class=""title-head""><span>Đăng nhập tài khoản</span></h1>
    <div class=""row"">
        <div class=""col-lg-6"">
            <div class=""page-login"">
                <div id=""login"">
                    <span>
                        Nếu bạn đã có tài khoản, đăng nhập tại đây.
                    </span>
        ");
            WriteLiteral("            <form accept-charset=\"UTF-8\" action=\"/Account/LoginPost\" id=\"customer_login\" method=\"post\">\r\n                        ");
            EndContext();
            BeginContext(1246, 23, false);
#line 35 "G:\ASP.NET\project_banhang\project_banhang\Views\Account\Login.cshtml"
                   Write(Html.AntiForgeryToken());

#line default
#line hidden
            EndContext();
            BeginContext(1269, 343, true);
            WriteLiteral(@"
                        <div class=""form-signup"">

                        </div>
                        <div class=""form-signup clearfix"">
                            <fieldset class=""form-group"">
                                <label>Email <span class=""required"">*</span></label>
                                <input type=""email""");
            EndContext();
            BeginWriteAttribute("pattern", " pattern=\"", 1612, "\"", 1663, 3);
            WriteAttributeValue("", 1622, "[a-z0-9._%+-]+", 1622, 14, true);
            WriteAttributeValue("", 1636, "@", 1636, 1, true);
            WriteAttributeValue("", 1638, "[a-z0-9.-]+\\.[a-z]{2,63}$", 1638, 25, true);
            EndWriteAttribute();
            BeginContext(1664, 2238, true);
            WriteLiteral(@" class=""form-control form-control-lg"" value="""" name=""email"" id=""customer_email"" placeholder=""Email"" required="""">
                            </fieldset>
                            <fieldset class=""form-group"">
                                <label>Mật khẩu <span class=""required"">*</span></label>
                                <input type=""password"" class=""form-control form-control-lg"" value="""" name=""password"" id=""customer_password"" placeholder=""Mật khẩu"" required="""">
                            </fieldset>



                            <div class=""pull-xs-left"" style=""margin-top: 25px;"">
                                <input class=""btn btn-style btn-primary"" type=""submit"" value=""Đăng nhập"">
                                <a href=""/Account/Register"" class=""btn-link-style btn-register"" style=""margin-left: 20px;text-decoration: underline; "">Đăng ký</a>
                            </div>
                        </div>
                    </form>

                    <div style=""margin-top: 5");
            WriteLiteral(@"px;"" id=""social_login_widget""><div id=""social_login"" style=""width: 280px; height: 120px;""><iframe id=""sa_iframe"" width=""280"" height=""120"" style=""border:none;"" src=""https://sociallogin.sapoapps.vn/sociallogin/block_login?store=memoryzone-com-vn.mysapo.net""></iframe></div></div>
                </div>


            </div>
        </div>
        <div class=""col-lg-6 h_recover"">

            <div id=""recover-password"" class=""form-signup page-login"">
                <span>
                    Bạn quên mật khẩu? Nhập địa chỉ email để lấy lại mật khẩu qua email.
                </span>
                <form accept-charset=""UTF-8"" action=""/account/recover"" id=""recover_customer_password"" method=""post"">
                    <input name=""FormType"" type=""hidden"" value=""recover_customer_password"">
                    <input name=""utf8"" type=""hidden"" value=""true"">
                    <div class=""form-signup"" style=""color: red;"">

                    </div>
                    <div class=""form-signup clearf");
            WriteLiteral("ix\">\r\n                        <fieldset class=\"form-group\">\r\n                            <label>Email <span class=\"required\">*</span></label>\r\n                            <input type=\"email\"");
            EndContext();
            BeginWriteAttribute("pattern", " pattern=\"", 3902, "\"", 3953, 3);
            WriteAttributeValue("", 3912, "[a-z0-9._%+-]+", 3912, 14, true);
            WriteAttributeValue("", 3926, "@", 3926, 1, true);
            WriteAttributeValue("", 3928, "[a-z0-9.-]+\\.[a-z]{2,63}$", 3928, 25, true);
            EndWriteAttribute();
            BeginContext(3954, 468, true);
            WriteLiteral(@" class=""form-control form-control-lg"" value="""" name=""Email"" id=""recover-email"" placeholder=""Email"" required="""">
                        </fieldset>
                    </div>
                    <div class=""action_bottom"">
                        <input class=""btn btn-style btn-primary"" style=""margin-top: 28px;"" type=""submit"" value=""Lấy lại mật khẩu"">

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
