#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3f4a21ae89b968c38905b35ba9de2f340ab9edd4"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Product_Detail), @"mvc.1.0.view", @"/Views/Product/Detail.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Product/Detail.cshtml", typeof(AspNetCore.Views_Product_Detail))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 7 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
using project_banhang.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"3f4a21ae89b968c38905b35ba9de2f340ab9edd4", @"/Views/Product/Detail.cshtml")]
    public class Views_Product_Detail : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
  
    ViewData["Title"] = "Details";
    Layout = "~/Views/_shared/_chiTiet.cshtml";

#line default
#line hidden
            BeginContext(94, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 8 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
  
    DataContext db = new DataContext();
    var _itemsList = db.ItemsList.OrderByDescending(tbl => tbl.id).ToList();

#line default
#line hidden
            BeginContext(254, 284, true);
            WriteLiteral(@"
<section class=""bread-crumb"">
    <div class=""container"">
        <div class=""row"">
            <div class=""col-xs-12"">
                <ul class=""breadcrumb"" itemscope="""" itemtype=""http://data-vocabulary.org/Breadcrumb"">
                    <li><strong><span itemprop=""title"">");
            EndContext();
            BeginContext(539, 10, false);
#line 18 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                  Write(Model.name);

#line default
#line hidden
            EndContext();
            BeginContext(549, 274, true);
            WriteLiteral(@"</span></strong></li>
                    <li>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section class=""product margin-top-20"" itemscope="""" itemtype=""http://schema.org/Product"">
    <meta itemprop=""url""");
            EndContext();
            BeginWriteAttribute("content", " content=\"", 823, "\"", 858, 2);
            WriteAttributeValue("", 833, "/Product/Detail/", 833, 16, true);
#line 27 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 849, Model.id, 849, 9, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(859, 28, true);
            WriteLiteral(">\r\n    <meta itemprop=\"name\"");
            EndContext();
            BeginWriteAttribute("content", " content=\"", 887, "\"", 908, 1);
#line 28 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 897, Model.name, 897, 11, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(909, 75, true);
            WriteLiteral(">\r\n    <meta itemprop=\"image\" content=\"\">\r\n    <meta itemprop=\"description\"");
            EndContext();
            BeginWriteAttribute("content", " content=\"", 984, "\"", 1026, 2);
#line 30 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("\r\n\t", 994, Html.Raw(Model.content), 997, 24, false);

#line default
#line hidden
            WriteAttributeValue("\r\n   ", 1021, "", 1026, 5, true);
            EndWriteAttribute();
            BeginContext(1027, 3047, true);
            WriteLiteral(@">
    <meta itemprop=""brand"" content=""Samsung"">
    <meta itemprop=""sku"" content=""MZ147254"">
    <meta itemprop=""mpn"" content=""12489065"">

    <div class=""container"">
        <div class=""row"">
            <div class=""details-product"">
                <div class=""col-lg-9 col-md-12 col-sm-12 col-xs-12"">
                    <div class=""rows"">
                        <div class=""product-detail-left product-images col-xs-12 col-sm-6 col-md-5 col-lg-5"">
                            <div class=""row"">
                                <div id=""sync1"" class=""owl-carousel owl-theme owl-loaded owl-drag"">





















                                    <div class=""owl-stage-outer"">
                                        <div class=""owl-stage"" style=""transform: translate3d(-1089px, 0px, 0px); transition: all 0s ease 0s; width: 3993px;"">
                                            <div class=""owl-item cloned"" style=""width: 363px;"">
                                               ");
            WriteLiteral(@" <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                                        <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-03.jpg?v=1568096819103"" src=""./chi tiết_files/860-pro-2-5-inch-03.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                                    </a>
                                                </div>
                                            </div><div class=""owl-item cloned"" style=""width: 363px;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                                        <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-04.jpg?v=1568096819103"" src=""./chi tiết_files/860-pro-2-5-inch-04.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                              ");
            WriteLiteral(@"      </a>
                                                </div>
                                            </div><div class=""owl-item cloned"" style=""width: 363px;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                                        <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-05.jpg?v=1568096819103"" src=""./chi tiết_files/860-pro-2-5-inch-05.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                                    </a>
                                                </div>
                                            </div><div class=""owl-item active"" style=""width: 363px;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                                        ");
            EndContext();
            BeginContext(4074, 102, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "e7599d3707dd43c1bef4e41d7018cc27", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            BeginWriteTagHelperAttribute();
            WriteLiteral("~/Upload/Products/");
#line 89 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                                    Write(Model.media);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __tagHelperExecutionContext.AddHtmlAttribute("data-img", Html.Raw(__tagHelperStringValueBuffer), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            AddHtmlAttributeValue("", 4126, "~/Upload/Products/", 4126, 18, true);
#line 89 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
AddHtmlAttributeValue("", 4144, Model.media, 4144, 12, false);

#line default
#line hidden
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "alt", 1, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
#line 89 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
AddHtmlAttributeValue("", 4163, Model.name, 4163, 11, false);

#line default
#line hidden
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(4176, 5093, true);
            WriteLiteral(@"
                                                    </a>
                                                </div>
                                            </div><div class=""owl-item"" style=""width: 363px;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                                        <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-02.jpg?v=1568096819103"" src=""./chi tiết_files/860-pro-2-5-inch-02.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                                    </a>
                                                </div>
                                            </div><div class=""owl-item"" style=""width: 363px;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                               ");
            WriteLiteral(@"         <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-03.jpg?v=1568096819103"" src=""./chi tiết_files/860-pro-2-5-inch-03.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                                    </a>
                                                </div>
                                            </div><div class=""owl-item"" style=""width: 363px;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                                        <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-04.jpg?v=1568096819103"" src=""./chi tiết_files/860-pro-2-5-inch-04.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                                    </a>
                                                </div>
                                            </div><div class=""owl-item"" style=""width: 363p");
            WriteLiteral(@"x;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                                        <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-05.jpg?v=1568096819103"" src=""./chi tiết_files/860-pro-2-5-inch-05.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                                    </a>
                                                </div>
                                            </div><div class=""owl-item cloned"" style=""width: 363px;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                                        <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-01.jpg?v=1539764764717"" src=""./chi tiết_files/860-pro-2-5-inch-01.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P25");
            WriteLiteral(@"6BW"">
                                                    </a>
                                                </div>
                                            </div><div class=""owl-item cloned"" style=""width: 363px;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                                                        <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-02.jpg?v=1568096819103"" src=""./chi tiết_files/860-pro-2-5-inch-02.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                                    </a>
                                                </div>
                                            </div><div class=""owl-item cloned"" style=""width: 363px;"">
                                                <div class=""item"">
                                                    <a href=""javascript:void(0)"">
                            ");
            WriteLiteral(@"                            <img data-img=""//bizweb.dktcdn.net/100/329/122/products/860-pro-2-5-inch-03.jpg?v=1568096819103"" src=""./chi tiết_files/860-pro-2-5-inch-03.jpg"" alt=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div><div class=""owl-nav disabled""><div class=""owl-prev""><svg width=""100%"" height=""100%"" viewBox=""0 0 11 20""><path style=""fill:none;stroke-width: 1px;stroke: #000;"" d=""M9.554,1.001l-8.607,8.607l8.607,8.606""></path></svg></div><div class=""owl-next""><svg width=""100%"" height=""100%"" viewBox=""0 0 11 20"" version=""1.1""><path style=""fill:none;stroke-width: 1px;stroke: #000;"" d=""M1.054,18.214l8.606,-8.606l-8.606,-8.607""></path></svg></div></div><div class=""owl-dots disabled""></div>
                                </div>

");
            EndContext();
            BeginContext(13157, 210, true);
            WriteLiteral("                            </div>\r\n                        </div>\r\n                        <div class=\"col-xs-12 col-sm-6 col-md-7 col-lg-7 details-pro\">\r\n                            <h1 class=\"title-product\">");
            EndContext();
            BeginContext(13368, 10, false);
#line 200 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                 Write(Model.name);

#line default
#line hidden
            EndContext();
            BeginContext(13378, 735, true);
            WriteLiteral(@"</h1>



                            <div class=""reviews_details_product"">
                                <div class=""bizweb-product-reviews-badge"" data-id=""12489065""></div>
                            </div>
                            <div itemprop=""offers"" itemscope="""" itemtype=""http://schema.org/Offer"">
                                <meta itemprop=""priceValidUntil"" content=""2030-11-05"">
                                <link itemprop=""url"" href=""https://www.memoryzone.com.vn/ssd-samsung-860-pro-series-256gb"">
                                <div class=""group-status"">
                                    <span class=""first_status"">
                                        Thương hiệu: <span class=""status_name"">");
            EndContext();
            BeginContext(14114, 13, false);
#line 212 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                          Write(ViewBag.brand);

#line default
#line hidden
            EndContext();
            BeginContext(14127, 356, true);
            WriteLiteral(@"</span>
                                    </span>
                                    <span class=""first_status"">
                                        &nbsp;|&nbsp; Tình trạng: <span class=""status_name availabel"">
                                            <span><link itemprop=""availability"" href=""https://schema.org/InStock"">Còn hàng</span>

");
            EndContext();
            BeginContext(15230, 138, true);
            WriteLiteral("\r\n\r\n                                        </span>\r\n                                    </span>\r\n                                </div>\r\n");
            EndContext();
#line 233 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                  
                                    var infor = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
                                

#line default
#line hidden
            BeginContext(15546, 32, true);
            WriteLiteral("                                ");
            EndContext();
#line 236 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                 if (Model.sale)
                                {
                                    var newprice = Model.price - Model.price * Model.discount / 100;

#line default
#line hidden
            BeginContext(15733, 220, true);
            WriteLiteral("                                    <div class=\"price-box clearfix\">\r\n\r\n                                        <span class=\"special-price\">\r\n                                            <span class=\"price product-price\">");
            EndContext();
            BeginContext(15954, 45, false);
#line 242 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                         Write(string.Format(infor, "{0:c0" + "}", newprice));

#line default
#line hidden
            EndContext();
            BeginContext(15999, 9, true);
            WriteLiteral("</span>\r\n");
            EndContext();
            BeginContext(16194, 361, true);
            WriteLiteral(@"                                        </span> <!-- Giá Khuyến mại -->
                                        <span class=""old-price"" itemprop=""priceSpecification"" itemscope="""" itemtype=""http://schema.org/priceSpecification"">
                                            <del class=""price product-price-old"">
                                                ");
            EndContext();
            BeginContext(16556, 48, false);
#line 248 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                           Write(string.Format(infor, "{0:c0" + "}", Model.price));

#line default
#line hidden
            EndContext();
            BeginContext(16604, 54, true);
            WriteLiteral("\r\n                                            </del>\r\n");
            EndContext();
            BeginContext(16840, 113, true);
            WriteLiteral("                                        </span> <!-- Giás gốc -->\r\n\r\n                                    </div>\r\n");
            EndContext();
#line 255 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                }
                                else
                                {

#line default
#line hidden
            BeginContext(17061, 220, true);
            WriteLiteral("                                    <div class=\"price-box clearfix\">\r\n\r\n                                        <span class=\"special-price\">\r\n                                            <span class=\"price product-price\">");
            EndContext();
            BeginContext(17282, 48, false);
#line 261 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                         Write(string.Format(infor, "{0:c0" + "}", Model.price));

#line default
#line hidden
            EndContext();
            BeginContext(17330, 126, true);
            WriteLiteral("</span>\r\n                                        </span> <!-- Giá Khuyến mại -->\r\n                                    </div>\r\n");
            EndContext();
#line 264 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                }

#line default
#line hidden
            BeginContext(17491, 247, true);
            WriteLiteral("                            </div>\r\n\r\n\r\n                            <div class=\"product-summary product_description margin-bottom-0\">\r\n                                <div class=\"rte description  rte-summary\">\r\n                                    ");
            EndContext();
            BeginContext(17739, 23, false);
#line 270 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                               Write(Html.Raw(Model.content));

#line default
#line hidden
            EndContext();
            BeginContext(17762, 342, true);
            WriteLiteral(@"

                                    <div id=""eJOY__extension_root"" style=""all: unset;"">&nbsp;</div>

                                </div>

                            </div>

                            <div class=""form-product col-sm-12"">
                                <form enctype=""multipart/form-data"" id=""add-to-cart-form""");
            EndContext();
            BeginWriteAttribute("action", " action=\"", 18104, "\"", 18132, 2);
            WriteAttributeValue("", 18113, "/Cart/Buy/", 18113, 10, true);
#line 279 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 18123, Model.id, 18123, 9, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(18133, 89, true);
            WriteLiteral(" method=\"post\" class=\"form-inline margin-bottom-0\">\r\n                                    ");
            EndContext();
            BeginContext(18223, 23, false);
#line 280 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                               Write(Html.AntiForgeryToken());

#line default
#line hidden
            EndContext();
            BeginContext(18246, 16529, true);
            WriteLiteral(@"
                                    <div class=""col-sm-6 col-xs-12 no-padding"">

                                        <div class=""box-variant clearfix "">

                                            <input type=""hidden"" name=""variantId"" value=""20443098"">

                                        </div>
                                    </div>
                                    <div class=""col-sm-6 col-xs-12 no-padding"">

                                    </div>
                                    <div class=""form-group form_button_details margin-top-5"">
                                        <div class=""form_product_content "">
                                            <div class=""soluong show"">
                                                <div class=""label_sl margin-bottom-10"">Số lượng:</div>
                                                <div class=""custom input_number_product custom-btn-number form-control"">
                                                    <button class=""b");
            WriteLiteral(@"tn_num num_1 button button_qty"" onclick=""var result = document.getElementById(&#39;qtym&#39;); var qtypro = result.value; if( !isNaN( qtypro ) &amp;&amp; qtypro &gt; 1 ) result.value--;return false;"" type=""button"">-</button>
                                                    <input type=""text"" id=""qtym"" name=""quantity"" onkeyup=""valid(this,&#39;numbers&#39;)"" onkeypress=""validate(event)"" class=""form-control prd_quantity"" min=""1"" value=""1"">
                                                    <button class=""btn_num num_2 button button_qty"" onclick=""var result = document.getElementById(&#39;qtym&#39;); var qtypro = result.value; if( !isNaN( qtypro )) result.value++;return false;"" type=""button"">+</button>
                                                </div>
                                            </div>

                                            <div class=""button_actions clearfix"">

                                                <button type=""submit"" class=""btn btn_base btn_add_cart btn-cart"">
");
            WriteLiteral(@"                                                    <span class=""text_1"">MUA NGAY</span>
                                                    <span class=""text_2"">Giao hàng miễn phí tận nơi</span>
                                                </button>

                                                <a class=""btn btn_base btn_call"" href=""tel:(028)73013878"">
                                                    <span class=""text_1"">GỌI ĐẶT HÀNG</span>

                                                    <span class=""text_2"">Vui lòng gọi ngay (028) 7301 3878</span>

                                                </a>
                                            </div>
                                        </div>

                                    </div>









                                    <style>
                                        /* selectors without product id */

                                        label[for=""product-select-option-9""] {
                       ");
            WriteLiteral(@"                     display: none !important;
                                        }

                                        #product-select-option-9 {
                                            display: none !important;
                                        }

                                        label[for=""product-selectors-option-9""] {
                                            display: none !important;
                                        }

                                        #product-selectors-option-9 {
                                            display: none !important;
                                        }

                                        .id-product-select-option-9 {
                                            display: none !important;
                                        }


                                        /* selectors with product id */

                                        label[for=""product-select-12489065-option-9""] {
        ");
            WriteLiteral(@"                                    display: none !important;
                                        }

                                        #product-select-12489065-option-9 {
                                            display: none !important;
                                        }


                                        label[for=""product-selectors-12489065-option-9""] {
                                            display: none !important;
                                        }

                                        #product-selectors-12489065-option-9 {
                                            display: none !important;
                                        }
                                    </style>
                                    <script>
                                        setTimeout(function () {
                                            $(""label:contains('BuyXDiscount')"").css(""display"", ""none"");
                                        }, 100)
       ");
            WriteLiteral(@"                                 setTimeout(function () {
                                            $(""label:contains('BuyXDiscount')"").css(""display"", ""none"");
                                        }, 200)
                                        setTimeout(function () {
                                            $(""label:contains('BuyXDiscount')"").css(""display"", ""none"");
                                        }, 300)
                                        setTimeout(function () {
                                            $(""label:contains('BuyXDiscount')"").css(""display"", ""none"");
                                        }, 500)
                                        setTimeout(function () {
                                            $(""label:contains('BuyXDiscount')"").css(""display"", ""none"");
                                        }, 1000)
                                    </script>
                                    <div class=""ab-buyx-detail-product"" data-productid=""12489065""></div");
            WriteLiteral(@">
                                    <script>
                                        if (window.app_buyxgety_view != undefined) {
                                            window.app_buyxgety_view();
                                        }
                                        function addToCartApp(variantId) {
                                            $.ajax({
                                                type: 'POST',
                                                url: '/cart/add.js',
                                                async: false,
                                                data: { variantId: variantId, quantity: 1 },
                                                dataType: 'json',
                                                error: addToCartFail,
                                                beforeSend: function () {
                                                },
                                                success: addToCartSuccess,
            ");
            WriteLiteral(@"                                    cache: false
                                            });
                                        }
                                    </script>
                                    <link href=""./chi tiết_files/BuyXGetYStyle"" rel=""stylesheet"" type=""text/css"" media=""all"">
                                    <div class=""app_buyx_promotion""></div>
                                    <div class=""abps-productdetail ab-hide"" ab-data-productid=""12489065""></div>

                                    <div id=""app-installmentsales-btn-buy"" style=""display:none"" customer-id=""0"" product-id=""12489065"">
                                        <input type=""button"" style=""float:left;"" onclick=""installmentsalesBtnBuy();"" class=""app-buy-btn"" value=""MUA TRẢ GÓP"">
                                        <br>
                                        <div class=""app_installsale_error_message"">Chỉ áp dụng thanh toán trả góp với 1 đơn vị sản phẩm</div>
                                 ");
            WriteLiteral(@"       <br>
                                        <div class=""app-installmentsales-box"">
                                            <span class=""app-installmentsales-box-title"">
                                                Bảng tính mua hàng trả góp (Tham khảo)
                                            </span>
                                            <div class=""app-installmentsales-full-line"">
                                                <span class=""half-text-left"">Giá trị sản phẩm: </span>
                                                <span class=""half-text-right app-installmentsales-variant-price"">2.050.000₫</span>
                                            </div>
                                            <div class=""app-installmentsales-full-line"">
                                                <span class=""half-text-left"">Chính sách trả góp: </span>
                                                <span class=""half-text-right app-installmentsales-month"">
                  ");
            WriteLiteral(@"                                  <select>
                                                    </select>
                                                </span>
                                            </div>
                                            <div class=""app-installmentsales-full-line"">
                                                <span class=""half-text-left"">Mức trả trước: </span>
                                                <span class=""half-text-right prepay-money""></span>
                                            </div>
                                            <div class=""app-installmentsales-full-line"">
                                                <span class=""money-per-month-label"">Số tiền cần thanh toán hàng tháng: &nbsp;</span> <b class=""money-per-month""></b>
                                            </div>
                                        </div>

                                        <select id=""app-installment-product-selectors"" name=""app-installmen");
            WriteLiteral(@"t-variantId"" style=""display:none"">

                                            <option variant-id=""20443098"" variant-price=""2050000.0000"">2.050.000₫</option>

                                        </select>
                                    </div>
                                    <script>
	window.ABInstallmentSale = window.ABInstallmentSale || {};
	window.ABInstallmentSale.ProductId = 12489065;
	window.ABInstallmentSale.CustomerId = 0;
	window.ABInstallmentSale.MoneyFormat = ""{{amount_no_decimals_with_comma_separator}}₫"";
                                    </script>
                                    <style>

                                        .app-installmentsales-box * {
                                            padding: 0;
                                            margin: 0;
                                            text-align: left;
                                            float: left;
                                            border: none;
                   ");
            WriteLiteral(@"                     }

                                        .app-installmentsales-box {
                                            padding: 15px;
                                            margin: 15px 0 15px 0;
                                            text-align: left;
                                            float: left;
                                            border: 1px solid #ccc;
                                            border-radius: 5px;
                                            max-width: 435px;
                                        }

                                        .app-installmentsales-box-title {
                                            width: 100%;
                                            margin-bottom: 10px;
                                            font-size: 1.5em;
                                        }

                                        .app-installmentsales-full-line {
                                            width: 100%;");
            WriteLiteral(@"
                                            line-height: 34px;
                                            float: left;
                                            margin-top: 10px;
                                        }

                                        .app-installmentsales-box .half-text-left {
                                            width: 40%;
                                            float: left;
                                        }

                                        .app-installmentsales-box .half-text-right {
                                            width: 60%;
                                            float: left;
                                        }

                                        .app-installmentsales-box .money-per-month-label {
                                            float: left;
                                        }

                                        .app-installmentsales-variant-price {
                           ");
            WriteLiteral(@"                 padding: 0 0 0 12px;
                                            border: 1px solid #ccc;
                                            color: #191515;
                                            border-radius: 5px;
                                            line-height: 32px;
                                        }

                                        .app-installmentsales-month {
                                            text-align: center;
                                            border: 1px solid #ccc;
                                            color: #191515;
                                            border-radius: 5px;
                                            line-height: 32px;
                                        }

                                        .app-installmentsales-variant-price * {
                                            color: #191515;
                                        }

                                        .app-installme");
            WriteLiteral(@"ntsales-month * {
                                            color: #191515;
                                        }

                                        .app-installmentsales-box select {
                                            padding: 0 8px;
                                            height: 32px;
                                            width: 100%;
                                            border: none;
                                            box-shadow: none;
                                            background-color: transparent;
                                            background-image: none;
                                        }

                                        .app-installmentsales-box .money-per-month {
                                            color: red;
                                        }

                                        #app-installmentsales-btn-buy {
                                            clear: both;
              ");
            WriteLiteral(@"                              float: left;
                                        }

                                            #app-installmentsales-btn-buy .app-buy-btn {
                                                padding: 10px 20px;
                                                border: none;
                                            }

                                            #app-installmentsales-btn-buy .app_installsale_error_message {
                                                color: red;
                                                float: left;
                                                display: none;
                                                -ms-word-wrap: break-word;
                                                word-wrap: break-word;
                                            }
                                    </style>
                                </form>
                            </div>













                         ");
            WriteLiteral("   <div class=\"thongtinkhuyenmai\">\r\n                                <div class=\"content rte rte-summary\">\r\n\r\n                                    ");
            EndContext();
            BeginContext(34776, 20, false);
#line 575 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                               Write(Html.Raw(Model.note));

#line default
#line hidden
            EndContext();
            BeginContext(34796, 1085, true);
            WriteLiteral(@"
                                </div>
                            </div>



                        </div>
                    </div>
                    <div class=""tab_h"">

                        <div class=""col-xs-12 col-lg-12 col-sm-12 col-md-12 no-padding"">
                            <!-- Nav tabs -->
                            <div class=""product-tab e-tabs"">
                                <ul class=""tabs tabs-title clearfix"">

                                    <li class=""tab-link current"" data-tab=""tab-1"">
                                        <h3><span>Mô tả sản phẩm</span></h3>
                                    </li>



                                </ul>

                                <div id=""tab-1"" class=""tab-content current"">
                                    <div class=""rte"">
                                        <div class=""product-well"">
                                            <div class=""ba-text-fpt"" id=""show_test"">
                          ");
            WriteLiteral("                      <span class=\"more-text\" id=\"more-text\">");
            EndContext();
            BeginContext(35882, 27, false);
#line 602 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                                  Write(Html.Raw(Model.description));

#line default
#line hidden
            EndContext();
            BeginContext(35909, 1914, true);
            WriteLiteral(@"</span>

                                            </div>

                                            <div class=""show-more"">
                                                <a class=""btn btn-default btn--view-more"">
                                                    <span class=""more-text"" id=""more"">Xem đầy đủ</span>
                                                    <span class=""less-text"" id=""less"">Thu gọn</span>
                                                </a>
                                            </div>
                                        </div>
                                        <script type=""text/javascript"">
                                            document.getElementById(""more"").addEventListener(""click"", function () {
                                                document.getElementById(""show_test"").removeAttribute(""class"");
                                                document.getElementById(""more"").setAttribute(""class"", ""less-text"");
                  ");
            WriteLiteral(@"                              document.getElementById(""less"").setAttribute(""class"", ""more-text"");
                                            });
                                            document.getElementById(""less"").addEventListener(""click"", function () {
                                                document.getElementById(""show_test"").setAttribute(""class"", ""ba-text-fpt"");
                                                document.getElementById(""more"").setAttribute(""class"", ""more-text"");
                                                document.getElementById(""less"").setAttribute(""class"", ""less-text"");
                                            })
                                        </script>

                                    </div>
                                </div>



                            </div>
                        </div>




");
            EndContext();
            BeginContext(37870, 5277, true);
            WriteLiteral(@"                        <div class=""fb-comments"" data-href=""http://hoanguyen-001-site1.itempurl.com/"" data-width=""870"" data-numposts=""5""></div>




                        <div id=""bizweb-product-reviews"" class=""bizweb-product-reviews"" data-id=""12489065"">

                            <div class=""title-bl"">
                                <h3>Đánh giá sản phẩm</h3>
                            </div>
                            <div id=""bizweb-product-reviews-sub"" style=""width:100%"">
                                <div class=""bizweb-product-reviews-summary"" id=""bizweb-product-reviews-summary"">
                                    <div>
                                        <meta itemprop=""name"" content=""SSD Samsung 860 Pro Series 256GB MZ-76P256BW"">
                                        <div class=""bpr-summary"" itemprop=""aggregateRating"" itemscope="""" itemtype=""http://schema.org/AggregateRating"">
                                            <meta content=""5"" itemprop=""ratingValue"">
           ");
            WriteLiteral(@"                                 <meta content=""5"" itemprop=""bestRating"">
                                            <meta content=""1"" itemprop=""worstRating"">
                                            <meta content=""2"" itemprop=""ratingCount"">
                                            <span class=""bpr-summary-average"">5</span>
                                            <div id=""bizweb-prv-summary-star"" class=""bizweb-product-reviews-star"" data-score=""5"" data-number=""5""></div>
                                            <div class=""bpr-summary-caption""></div>
                                        </div>
                                        <div itemprop=""review"" itemtype=""http://schema.org/Review"" itemscope="""">
                                            <div itemprop=""author"" itemtype=""http://schema.org/Person"" itemscope="""">
                                                <meta itemprop=""name"" content=""Memoryzone - Professional in memory"">
                                            </div>");
            WriteLiteral(@"
                                        </div>
                                    </div>
                                </div>
                                <span class=""product-reviews-summary-actions"">
                                </span>
                                <div class=""bizweb-product-reviews-form"" id=""bpr-form_12489065"" style=""display:none;"">
                                </div>
                                <div style=""display:none;"" id=""bpr-thanks"" class=""bizweb-product-reviews-form"">
                                </div>
                                <div id=""bpr-list"" class=""bizweb-product-reviews-list"">
                                </div>
                                <div id=""bpr-more-reviews"">
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class=""col-lg-3 col-md-3 col-sm-12 col-xs-12 hidden-xs hidden-sm hidden-md"">
      ");
            WriteLiteral(@"              <div class=""right_module margin-bottom-50"">
                        <div class=""module_service_details"">
                            <div class=""wrap_module_service"">

                                <div class=""item_service"">
                                    <div class=""wrap_item_"">
                                        <div class=""content_service"">
                                            <p>Giao hàng miễn phí toàn quốc</p>
                                            <span>cho đơn hàng giá trị từ 300.000đ trở lên</span>
                                        </div>
                                    </div>
                                </div>


                                <div class=""item_service"">
                                    <div class=""wrap_item_"">
                                        <div class=""content_service"">
                                            <p>Hưng Yên</p>
                                            <span>Nhận hàng từ 6 đến 24h sa");
            WriteLiteral(@"u khi đặt hàng</span>
                                        </div>
                                    </div>
                                </div>


                                <div class=""item_service"">
                                    <div class=""wrap_item_"">
                                        <div class=""content_service"">
                                            <p>HÀ NỘI</p>
                                            <span>Nhận hàng từ 6 đến 24h sau khi đặt hàng</span>
                                        </div>
                                    </div>
                                </div>


                                <div class=""item_service"">
                                    <div class=""wrap_item_"">
                                        <div class=""content_service"">
                                            <p>CÁC TỈNH THÀNH KHÁC</p>
                                            <span>nhận hàng từ 24 đến 96h sau khi đặt hàng</span>
               ");
            WriteLiteral("                         </div>\r\n                                    </div>\r\n\r\n                                </div>\r\n                            </div>\r\n\r\n");
            EndContext();
            BeginContext(45472, 475, true);
            WriteLiteral(@"
                        </div>
                    </div>
                </div>





                <div class=""col-lg-12 related-product margin-top-20 xs-margin-top-0 margin-bottom-30"">
                    <div class=""section_prd_feature section_base"">
                        <div class=""border_bottom_title clearfix"">
                        </div>
                        <div class=""title_top_menu"">
                            <h3 class=""title-head""><a");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 45947, "\"", 45983, 2);
            WriteAttributeValue("", 45954, "/Product/Category/", 45954, 18, true);
#line 815 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 45972, ViewBag.id, 45972, 11, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(45984, 566, true);
            WriteLiteral(@">Sản phẩm cùng loại</a></h3>
                        </div>








                        <div class=""products product_related products-view-grid-bb owl-carousel owl-theme products-view-grid not-dot2 owl-loaded owl-drag"" data-dot=""false"" data-nav=""false"" data-lg-items=""5"" data-md-items=""4"" data-sm-items=""3"" data-xs-items=""2"" data-margin=""15"">

                            <div class=""owl-stage-outer"">
                                <div class=""owl-stage"" style=""transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 1896px;"">
");
            EndContext();
#line 829 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                     foreach (var _sameiteam in ViewBag.list_record)
                                    {

#line default
#line hidden
            BeginContext(46675, 598, true);
            WriteLiteral(@"                                        <div class=""owl-item active"" style=""width: 222px; margin-right: 15px;"">
                                            <div class=""item saler_item"">
                                                <div class=""owl_item_product product-col-1"" style=""border-right: 1px solid rgb(235, 235, 235);"">
                                                    <div class=""product-box-h"">
                                                        <div class=""product-thumbnail"">
                                                            <a class=""image_link display_flex""");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 47273, "\"", 47310, 2);
            WriteAttributeValue("", 47280, "/Product/Detail/", 47280, 16, true);
#line 836 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 47296, _sameiteam.id, 47296, 14, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginWriteAttribute("title", " title=\"", 47311, "\"", 47335, 1);
#line 836 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 47319, _sameiteam.name, 47319, 16, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(47336, 67, true);
            WriteLiteral(">\r\n                                                                ");
            EndContext();
            BeginContext(47403, 122, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "6472a3ba65a3458b8392f26384041a29", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            AddHtmlAttributeValue("", 47413, "~/Upload/Products/", 47413, 18, true);
#line 837 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
AddHtmlAttributeValue("", 47431, _sameiteam.media, 47431, 17, false);

#line default
#line hidden
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            BeginWriteTagHelperAttribute();
            WriteLiteral("~/Upload/Products/");
#line 837 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                                                                                           Write(_sameiteam.media);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __tagHelperExecutionContext.AddHtmlAttribute("data-lazyload", Html.Raw(__tagHelperStringValueBuffer), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "alt", 1, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
#line 837 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
AddHtmlAttributeValue("", 47507, _sameiteam.name, 47507, 16, false);

#line default
#line hidden
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(47525, 152, true);
            WriteLiteral("\r\n                                                            </a>\r\n\r\n                                                            <!-- Tag giá sốc -->\r\n");
            EndContext();
#line 841 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                             if (_sameiteam.sale)
                                                            {

#line default
#line hidden
            BeginContext(47823, 270, true);
            WriteLiteral(@"                                                                <div class=""tagdacbiet_sale sale-flash"">

                                                                    <div class=""font16"">
                                                                        ");
            EndContext();
            BeginContext(48094, 19, false);
#line 846 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                   Write(_sameiteam.discount);

#line default
#line hidden
            EndContext();
            BeginContext(48113, 153, true);
            WriteLiteral("%\r\n\r\n                                                                    </div>\r\n                                                                </div>\r\n");
            EndContext();
#line 850 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                            }

#line default
#line hidden
            BeginContext(48329, 524, true);
            WriteLiteral(@"
                                                            <!-- End tag giá sốc -->
                                                            <!-- Tag Mã KM -->
                                                            <!-- End Tag Mã KM -->
                                                        </div>
                                                        <div class=""product-info a-left"">
                                                            <h3 class=""product-name""><a class=""height_name text2line""");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 48853, "\"", 48890, 2);
            WriteAttributeValue("", 48860, "/Product/Detail/", 48860, 16, true);
#line 857 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 48876, _sameiteam.id, 48876, 14, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginWriteAttribute("title", " title=\"", 48891, "\"", 48915, 1);
#line 857 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 48899, _sameiteam.name, 48899, 16, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(48916, 1, true);
            WriteLiteral(">");
            EndContext();
            BeginContext(48918, 15, false);
#line 857 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                                                                                                                                Write(_sameiteam.name);

#line default
#line hidden
            EndContext();
            BeginContext(48933, 196, true);
            WriteLiteral("</a></h3>\r\n\r\n                                                            <div class=\"product-hides\">\r\n                                                                <div class=\"product-hide\">\r\n\r\n");
            EndContext();
#line 862 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                      

                                                                        if (_sameiteam.sale)
                                                                        {
                                                                            double newprice = _sameiteam.price - _sameiteam.price * _sameiteam.discount / 100;

#line default
#line hidden
            BeginContext(49532, 337, true);
            WriteLiteral(@"                                                                            <div class=""price-box clearfix"">
                                                                                <div class=""special-price"">
                                                                                    <span class=""price product-price"">");
            EndContext();
            BeginContext(49870, 45, false);
#line 869 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                                                                 Write(string.Format(infor, "{0:c0" + "}", newprice));

#line default
#line hidden
            EndContext();
            BeginContext(49915, 454, true);
            WriteLiteral(@"</span>
                                                                                </div>

                                                                                <div class=""old-price"">
                                                                                    <span class=""price product-price-old"">
                                                                                        <span class=""price product-price-old"">");
            EndContext();
            BeginContext(50370, 53, false);
#line 874 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                                                                         Write(string.Format(infor, "{0:c0" + "}", _sameiteam.price));

#line default
#line hidden
            EndContext();
            BeginContext(50423, 278, true);
            WriteLiteral(@"</span>
                                                                                    </span>
                                                                                </div>


                                                                            </div>
");
            EndContext();
#line 880 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                        }
                                                                        else
                                                                        {

#line default
#line hidden
            BeginContext(50929, 337, true);
            WriteLiteral(@"                                                                            <div class=""price-box clearfix"">
                                                                                <div class=""special-price"">
                                                                                    <span class=""price product-price"">");
            EndContext();
            BeginContext(51267, 53, false);
#line 885 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                                                                 Write(string.Format(infor, "{0:c0" + "}", _sameiteam.price));

#line default
#line hidden
            EndContext();
            BeginContext(51320, 183, true);
            WriteLiteral("</span>\r\n                                                                                </div>\r\n\r\n                                                                            </div>\r\n");
            EndContext();
#line 889 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                        }
                                                                    

#line default
#line hidden
            BeginContext(51649, 324, true);
            WriteLiteral(@"


                                                                </div>
                                                            </div>
                                                            <div class=""product-action clearfix hidden-xs"">
                                                                <form");
            EndContext();
            BeginWriteAttribute("action", " action=\"", 51973, "\"", 52006, 2);
            WriteAttributeValue("", 51982, "/Cart/Buy/", 51982, 10, true);
#line 897 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 51992, _sameiteam.id, 51992, 14, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(52007, 181, true);
            WriteLiteral(" method=\"post\" class=\"variants form-nut-grid\" data-id=\"product-actions-15122743\" enctype=\"multipart/form-data\">\r\n                                                                    ");
            EndContext();
            BeginContext(52189, 23, false);
#line 898 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                               Write(Html.AntiForgeryToken());

#line default
#line hidden
            EndContext();
            BeginContext(52212, 188, true);
            WriteLiteral("\r\n                                                                    <div>\r\n\r\n                                                                        <input type=\"hidden\" name=\"variantId\"");
            EndContext();
            BeginWriteAttribute("value", " value=\"", 52400, "\"", 52422, 1);
#line 901 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 52408, _sameiteam.id, 52408, 14, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(52423, 252, true);
            WriteLiteral(">\r\n                                                                        <input type=\"hidden\" name=\"quantity\" value=\"1\">\r\n                                                                        <button class=\"btn-buy btn-cart btn btn-circle left-to \"");
            EndContext();
            BeginWriteAttribute("title", " title=\"", 52675, "\"", 52697, 1);
#line 903 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 52683, _sameiteam.id, 52683, 14, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(52698, 318, true);
            WriteLiteral(@">
                                                                            <i class=""fa fa-shopping-basket""></i>Mua ngay
                                                                        </button>


                                                                        <a data-toggle=""tooltip"" title=""""");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 53016, "\"", 53053, 2);
            WriteAttributeValue("", 53023, "/Product/Detail/", 53023, 16, true);
#line 908 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
WriteAttributeValue("", 53039, _sameiteam.id, 53039, 14, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(53054, 14, true);
            WriteLiteral(" data-handle=\"");
            EndContext();
            BeginContext(53069, 15, false);
#line 908 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                                                                                                                                        Write(_sameiteam.name);

#line default
#line hidden
            EndContext();
            BeginContext(53084, 941, true);
            WriteLiteral(@""" class=""xem_nhanh btn-circle btn_view btn right-to quick-view hidden-xs hidden-sm hidden-md"" data-original-title=""Xem nhanh"">
                                                                            <i class=""fa fa-eye""></i>
                                                                        </a>

                                                                    </div>
                                                                </form>
                                                            </div>

                                                            <div class=""bizweb-product-reviews-badge"" data-id=""15122743""></div>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
");
            EndContext();
#line 923 "G:\ASP.NET\project_banhang\project_banhang\Views\Product\Detail.cshtml"
                                    }

#line default
#line hidden
            BeginContext(54064, 441, true);
            WriteLiteral(@"                                </div>
                            </div><div class=""owl-nav""><div class=""owl-prev disabled""> </div><div class=""owl-next""> </div></div><div class=""owl-dots""><div class=""owl-dot active""><span></span></div><div class=""owl-dot""><span></span></div></div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

</section>



");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
