#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9f19678d6903d48199b3483986a16786167fe052"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_ItemsList_List), @"mvc.1.0.view", @"/Areas/Admin/Views/ItemsList/List.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/Admin/Views/ItemsList/List.cshtml", typeof(AspNetCore.Areas_Admin_Views_ItemsList_List))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
#line 14 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
using System.Linq;

#line default
#line hidden
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 8 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
using project_banhang.Models;

#line default
#line hidden
#line 10 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
using X.PagedList.Mvc.Core;

#line default
#line hidden
#line 16 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
using System.IO;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"9f19678d6903d48199b3483986a16786167fe052", @"/Areas/Admin/Views/ItemsList/List.cshtml")]
    public class Areas_Admin_Views_ItemsList_List : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<X.PagedList.IPagedList<ItemsList>>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("style", new global::Microsoft.AspNetCore.Html.HtmlString("max-height:50px;max-width:50px;"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
  
    ViewData["Title"] = "List";
    Layout = "~/Areas/Admin/Views/_share/_layout.cshtml";

#line default
#line hidden
            BeginContext(101, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(426, 6011, true);
            WriteLiteral(@"
<article class=""content items-list-page"">
    <div class=""title-search-block"">
        <div class=""title-block"">
            <div class=""row"">
                <div class=""col-md-3"">
                    <h3 class=""title"">
                        Items <a href=""/Admin/ItemsList/Add"" class=""btn btn-primary btn-sm rounded-s""> Add New </a>
                        <!--
                    -->
                        <div class=""action dropdown"">
                            <button class=""btn  btn-sm rounded-s btn-secondary dropdown-toggle"" type=""button"" id=""dropdownMenu1"" data-toggle=""dropdown"" aria-haspopup=""true"" aria-expanded=""false""> More actions... </button>
                            <div class=""dropdown-menu"" aria-labelledby=""dropdownMenu1"">
                                <a class=""dropdown-item"" href=""https://modularcode.io/modular-admin-html/items-list.html#""><i class=""fa fa-pencil-square-o icon""></i>Mark as a draft</a>
                                <a class=""dropdown-item"" href=""https:/");
            WriteLiteral(@"/modularcode.io/modular-admin-html/items-list.html#"" data-toggle=""modal"" data-target=""#confirm-modal""><i class=""fa fa-close icon""></i>Delete</a>
                            </div>
                        </div>
                    </h3>
                    <p class=""title-description""> List of sample items - e.g. books, movies, events, etc... </p>
                </div>
                <div class=""col-md-7"">
                    <div class=""items-search"">
                        <form class=""form-inline"">
                            <div class=""input-group "">
                                <input type=""text"" class=""form-control boxed rounded-l "" placeholder=""Search for..."" style=""height:33px"">
                                <span class=""input-group-btn"">
                                    <button class=""btn btn-secondary rounded-s"" type=""button"">
                                        <i class=""fa fa-search""></i>
                                    </button>
                                <");
            WriteLiteral(@"/span>
                            </div>
                        </form>
                    </div>
                </div>

                <div id=""sort-by"" class=""col-sm-2"">
                    <select class=""form-control"" onchange=""location.href='?group='+this.value;"">
                        <option value=""0"">Mặc định</option>
                        <option value=""asc"">A → Z</option>
                        <option value=""desc"">Z → A</option>
                        <option value=""priceAsc"">Giá tăng dần</option>
                        <option value=""priceDesc"">Giá giảm dần</option>
                        <option value=""productNew"">Hàng mới nhất</option>
                        <option value=""productOld"">Hàng cũ nhất</option>
                    </select>
                </div>
            </div>
        </div>


        <div class=""card items"">
            <ul class=""item-list striped"">
                <li class=""item item-list-header"">
                    <div class=""item-row""");
            WriteLiteral(@">
                        <div class=""item-col fixed item-col-check"">
                            <label class=""item-check"" id=""select-all-items"">
                                <input type=""checkbox"" class=""checkbox"">
                                <span></span>
                            </label>
                        </div>
                        <div class=""item-col item-col-header fixed item-col-img md"">
                            <div>
                                <span>Media</span>
                            </div>
                        </div>
                        <div class=""item-col item-col-header item-col-title"">
                            <div>
                                <span>Name</span>
                            </div>
                        </div>

                        <div class=""item-col item-col-header item-col-category"">
                            <div class=""no-overflow"">
                                <span>Thương hiệu</span>
            ");
            WriteLiteral(@"                </div>
                        </div>

                        <div class=""item-col item-col-header item-col-category"">
                            <div class=""no-overflow"">
                                <span>Category</span>
                            </div>
                        </div>

                        <div class=""item-col item-col-header item-price"">
                            <div class=""no-overflow"">
                                <span>Price</span>
                            </div>
                        </div>

                        <div class=""item-col item-col-header item-price"">
                            <div>
                                <span>Discount (%)</span>
                            </div>
                        </div>

                        <div class=""item-col item-col-header item-col-sales"">
                            <div>
                                <span>Sale</span>
                            </div>
            ");
            WriteLiteral(@"            </div>


                        <div class=""item-col item-col-header item-col-check"">
                            <div>
                                <span>Hot</span>
                            </div>
                        </div>

                        <div class=""item-col item-col-header item-col-date"">
                            <div>
                                <span>Published</span>
                            </div>
                        </div>

                        <div class=""item-col item-col-header fixed item-col-actions-dropdown"">
                        </div>
                        <div class=""item-col fixed item-col-actions-dropdown"">
                            <div class=""item-actions-dropdown"">

                            </div>
                        </div>
                    </div>
                </li>
");
            EndContext();
#line 140 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                 foreach (var item in Model)
                {

#line default
#line hidden
            BeginContext(6502, 643, true);
            WriteLiteral(@"                    <li class=""item item-list-header"">
                        <div class=""item-row"">

                            <div class=""item-col fixed item-col-check"">
                                <label class=""item-check"" id=""select-all-items"">
                                    <input type=""checkbox"" class=""checkbox"">
                                    <span></span>
                                </label>
                            </div>

                            <div class=""item-col item-col-header fixed item-col-img md"">
                                <div>
                                    <span>
");
            EndContext();
#line 155 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                         if (System.IO.File.Exists(Directory.GetCurrentDirectory() + "\\wwwroot\\Upload\\Products\\" + @item.media))
                                        {

#line default
#line hidden
            BeginContext(7338, 44, true);
            WriteLiteral("                                            ");
            EndContext();
            BeginContext(7382, 83, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "170b73258a1b4a899c84b6c1a997bbef", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            AddHtmlAttributeValue("", 7392, "~/Upload/Products/", 7392, 18, true);
#line 157 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
AddHtmlAttributeValue("", 7410, item.media, 7410, 11, false);

#line default
#line hidden
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(7465, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 158 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                        }

#line default
#line hidden
            BeginContext(7510, 287, true);
            WriteLiteral(@"                                    </span>
                                </div>
                            </div>

                            <div class=""item-col item-col-header item-col-title"">
                                <div>
                                    <span>");
            EndContext();
            BeginContext(7798, 9, false);
#line 165 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                     Write(item.name);

#line default
#line hidden
            EndContext();
            BeginContext(7807, 276, true);
            WriteLiteral(@"</span>
                                </div>
                            </div>

                            <div class=""item-col item-col-header item-col-category"">
                                <div class=""no-overflow"">
                                    <span>
");
            EndContext();
#line 172 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                           DataContext db = new DataContext();
                                            var _brand = db.brand.Where(tbl => tbl.id == item.id_brand).FirstOrDefault();
                                            if (_brand != null)
                                            { 

#line default
#line hidden
            BeginContext(8404, 11, false);
#line 175 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                               Write(_brand.name);

#line default
#line hidden
            EndContext();
#line 175 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                                                       }
                                        

#line default
#line hidden
            BeginContext(8468, 312, true);
            WriteLiteral(@"                                    </span>
                                </div>
                            </div>

                            <div class=""item-col item-col-header item-col-category"">
                                <div class=""no-overflow"">
                                    <span>
");
            EndContext();
#line 184 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                          

                                            var category = db.ItemsCategories.Where(tbl => tbl.id == item.id_category).FirstOrDefault();
                                            if (category != null)
                                            { 

#line default
#line hidden
            BeginContext(9084, 13, false);
#line 188 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                               Write(category.name);

#line default
#line hidden
            EndContext();
#line 188 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                                                         }
                                        

#line default
#line hidden
            BeginContext(9150, 123, true);
            WriteLiteral("                                    </span>\r\n                                </div>\r\n                            </div>\r\n\r\n");
            EndContext();
            BeginContext(9973, 184, true);
            WriteLiteral("\r\n                            <div class=\"item-col item-col-header item-price\">\r\n                                <div class=\"no-overflow\">\r\n                                    <span>\r\n");
            EndContext();
#line 209 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                         if (item.price != null)
                                        {

#line default
#line hidden
            BeginContext(10271, 37, false);
#line 210 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                          Write(string.Format("{0:#,#.}", item.price));

#line default
#line hidden
            EndContext();
#line 210 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                                                                            }

#line default
#line hidden
            BeginContext(10318, 285, true);
            WriteLiteral(@"                                    </span>
                                </div>
                            </div>

                            <div class=""item-col item-col-header item-price"">
                                <div>
                                    <span>
");
            EndContext();
#line 218 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                         if (item.sale == true)
                                        {

#line default
#line hidden
            BeginContext(10716, 13, false);
#line 219 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                          Write(item.discount);

#line default
#line hidden
            EndContext();
#line 219 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                                                    }

#line default
#line hidden
            BeginContext(10739, 289, true);
            WriteLiteral(@"                                    </span>
                                </div>
                            </div>

                            <div class=""item-col item-col-header item-col-sales"">
                                <div>
                                    <span>
");
            EndContext();
#line 227 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                         if (item.sale == true)
                                        {

#line default
#line hidden
            BeginContext(11140, 27, true);
            WriteLiteral("<i class=\"fa fa-check\"></i>");
            EndContext();
#line 228 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                                                                 }

#line default
#line hidden
            BeginContext(11177, 291, true);
            WriteLiteral(@"                                    </span>
                                </div>
                            </div>


                            <div class=""item-col item-col-header item-col-check"">
                                <div>
                                    <span>
");
            EndContext();
#line 237 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                         if (item.hot == true)
                                        {

#line default
#line hidden
            BeginContext(11579, 27, true);
            WriteLiteral("<i class=\"fa fa-check\"></i>");
            EndContext();
#line 238 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                                                                 }

#line default
#line hidden
            BeginContext(11616, 328, true);
            WriteLiteral(@"                                    </span>
                                </div>
                            </div>

                            <div class=""item-col item-col-header item-col-date"">
                                <div>
                                    <span>
                                        ");
            EndContext();
            BeginContext(11945, 14, false);
#line 246 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                                   Write(item.published);

#line default
#line hidden
            EndContext();
            BeginContext(11959, 1139, true);
            WriteLiteral(@"
                                    </span>
                                </div>
                            </div>
                            <div class=""item-col item-col-header fixed item-col-actions-dropdown""></div>
                            <div class=""item-col fixed item-col-actions-dropdown"">
                                <div class=""item-actions-dropdown"">
                                    <a class=""item-actions-toggle-btn"">
                                        <span class=""inactive"">
                                            <i class=""fa fa-cog""></i>
                                        </span>
                                        <span class=""active"">
                                            <i class=""fa fa-chevron-circle-right""></i>
                                        </span>
                                    </a>
                                    <div class=""item-actions-block"">
                                        <ul class=""item-actions-list"">
");
            WriteLiteral("                                            <li>\r\n                                                <a class=\"remove\"");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 13098, "\"", 13140, 2);
            WriteAttributeValue("", 13105, "/Admin/ItemsList/Delete?id=", 13105, 27, true);
#line 264 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
WriteAttributeValue("", 13132, item.id, 13132, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(13141, 355, true);
            WriteLiteral(@" onclick=""return window.confirm('Are you sure?');"">
                                                    <i class=""fa fa-trash-o ""></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a class=""edit""");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 13496, "\"", 13536, 2);
            WriteAttributeValue("", 13503, "/Admin/ItemsList/Edit?id=", 13503, 25, true);
#line 269 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
WriteAttributeValue("", 13528, item.id, 13528, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(13537, 416, true);
            WriteLiteral(@">
                                                    <i class=""fa fa-pencil""></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
");
            EndContext();
#line 279 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
                }

#line default
#line hidden
            BeginContext(13972, 16, true);
            WriteLiteral("                ");
            EndContext();
            BeginContext(13989, 81, false);
#line 280 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsList\List.cshtml"
           Write(Html.PagedListPager(Model, page => Url.Action("List", "ItemsList", new { page })));

#line default
#line hidden
            EndContext();
            BeginContext(14070, 37, true);
            WriteLiteral("\r\n            </ul>\r\n        </div>\r\n");
            EndContext();
            BeginContext(15476, 14, true);
            WriteLiteral("</article>\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<X.PagedList.IPagedList<ItemsList>> Html { get; private set; }
    }
}
#pragma warning restore 1591
