#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "72567cb46f327548106762cf880d420b4014ca23"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_ItemsCategories_List), @"mvc.1.0.view", @"/Areas/Admin/Views/ItemsCategories/List.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Areas/Admin/Views/ItemsCategories/List.cshtml", typeof(AspNetCore.Areas_Admin_Views_ItemsCategories_List))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 8 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
using project_banhang.Models;

#line default
#line hidden
#line 10 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
using X.PagedList.Mvc.Core;

#line default
#line hidden
#line 14 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
using System.IO;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"72567cb46f327548106762cf880d420b4014ca23", @"/Areas/Admin/Views/ItemsCategories/List.cshtml")]
    public class Areas_Admin_Views_ItemsCategories_List : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<X.PagedList.IPagedList<ItemsCategories>>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("style", new global::Microsoft.AspNetCore.Html.HtmlString("max-height:50px;max-width:50px;"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
  
    ViewData["Title"] = "List";
    Layout = "~/Areas/Admin/Views/_share/_layout.cshtml";

#line default
#line hidden
            BeginContext(101, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(387, 3748, true);
            WriteLiteral(@"
<article class=""content items-list-page"">
    <div class=""title-search-block"">
        <div class=""title-block"">
            <div class=""row"">
                <div class=""col-md-6"">
                    <h3 class=""title"">
                        Items <a href=""/Admin/ItemsCategories/Add"" class=""btn btn-primary btn-sm rounded-s"" title=""Thêm danh mục""> Thêm danh mục mới </a>
                        <!---->
                        <div class=""action dropdown"">
                            <button class=""btn  btn-sm rounded-s btn-secondary dropdown-toggle"" type=""button"" id=""dropdownMenu1"" data-toggle=""dropdown"" aria-haspopup=""true"" aria-expanded=""false""> More actions... </button>
                            <div class=""dropdown-menu"" aria-labelledby=""dropdownMenu1"">
                                <a class=""dropdown-item"" href=""https://modularcode.io/modular-admin-html/items-list.html#""><i class=""fa fa-pencil-square-o icon""></i>Mark as a draft</a>
                                <a class=""dropdown-ite");
            WriteLiteral(@"m"" href=""https://modularcode.io/modular-admin-html/items-list.html#"" data-toggle=""modal"" data-target=""#confirm-modal""><i class=""fa fa-close icon""></i>Delete</a>
                            </div>
                        </div>
                    </h3>
                    <p class=""title-description""> List of sample items - e.g. books, movies, events, etc... </p>
                </div>
            </div>
        </div>
        <div class=""items-search"">
            <form class=""form-inline"">
                <div class=""input-group"">
                    <input type=""text"" class=""form-control boxed rounded-s"" placeholder=""Search for..."" style=""height:33px"">
                    <span class=""input-group-btn"">
                        <button class=""btn btn-secondary rounded-s"" type=""button"">
                            <i class=""fa fa-search""></i>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <div class=""c");
            WriteLiteral(@"ard items"">
        <ul class=""item-list striped"">
            <li class=""item item-list-header"">
                <div class=""item-row"">
                    <div class=""item-col fixed item-col-check"">
                        <label class=""item-check"" id=""select-all-items"">
                            <input type=""checkbox"" class=""checkbox"">
                            <span></span>
                        </label>
                    </div>

                    <div class=""item-col item-col-header item-image"">
                        <div>
                            <span>Ảnh đại diện</span>
                        </div>
                    </div>

                    <div class=""item-col item-col-header item-col-category"">
                        <div>
                            <span>Tên danh mục</span>
                        </div>
                    </div>

                    <div class=""item-col item-col-header item-col-check"">
                        <div>
                ");
            WriteLiteral(@"            <span>Show Home</span>
                        </div>
                    </div>

                    <div class=""item-col item-col-header item-col-check"">
                        <div>
                            <span>Hot</span>
                        </div>
                    </div>

                    <div class=""item-col item-col-header fixed item-col-actions-dropdown"">
                    </div>
                    <div class=""item-col fixed item-col-actions-dropdown"">
                        <div class=""item-actions-dropdown"">

                        </div>
                    </div>
                </div>
            </li>

");
            EndContext();
#line 94 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
             foreach (var item in Model)
            {

#line default
#line hidden
            BeginContext(4192, 586, true);
            WriteLiteral(@"                <li class=""item item-list-header"">
                    <div class=""item-row"">
                        <div class=""item-col fixed item-col-check"">
                            <label class=""item-check"" id=""select-all-items"">
                                <input type=""checkbox"" class=""checkbox"">
                                <span></span>
                            </label>
                        </div>

                        <div class=""item-col item-col-header item-image"">
                            <div>
                                <span>
");
            EndContext();
#line 108 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
                                     if (System.IO.File.Exists(Directory.GetCurrentDirectory() + "\\wwwroot\\Upload\\Category-Thum\\" + @item.thumnails))
                                    {

#line default
#line hidden
            BeginContext(4972, 40, true);
            WriteLiteral("                                        ");
            EndContext();
            BeginContext(5012, 92, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "b75fcabbef024c7ab0e2229099b49947", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            AddHtmlAttributeValue("", 5022, "~/Upload/Category-Thum/", 5022, 23, true);
#line 110 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
AddHtmlAttributeValue("", 5045, item.thumnails, 5045, 15, false);

#line default
#line hidden
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(5104, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 111 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
                                    }

#line default
#line hidden
            BeginContext(5145, 266, true);
            WriteLiteral(@"                                </span>
                            </div>
                        </div>

                        <div class=""item-col item-col-header item-col-category"">
                            <div>
                                <span>");
            EndContext();
            BeginContext(5412, 9, false);
#line 118 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
                                 Write(item.name);

#line default
#line hidden
            EndContext();
            BeginContext(5421, 233, true);
            WriteLiteral("</span>\r\n                            </div>\r\n                        </div>\r\n\r\n                        <div class=\"item-col item-col-header item-col-check\">\r\n                            <div>\r\n                                <span>\r\n");
            EndContext();
#line 125 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
                                     if (item.showhome)
                                    {

#line default
#line hidden
            BeginContext(5754, 27, true);
            WriteLiteral("<i class=\"fa fa-check\"></i>");
            EndContext();
#line 126 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
                                                                             }

#line default
#line hidden
            BeginContext(5791, 267, true);
            WriteLiteral(@"                                </span>
                            </div>
                        </div>


                        <div class=""item-col item-col-header item-col-check"">
                            <div>
                                <span>
");
            EndContext();
#line 135 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
                                     if (item.hot)
                                    {

#line default
#line hidden
            BeginContext(6153, 27, true);
            WriteLiteral("<i class=\"fa fa-check\"></i>");
            EndContext();
#line 136 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
                                                                             }

#line default
#line hidden
            BeginContext(6190, 1067, true);
            WriteLiteral(@"                                </span>
                            </div>
                        </div>

                        <div class=""item-col item-col-header fixed item-col-actions-dropdown""></div>
                        <div class=""item-col fixed item-col-actions-dropdown"">
                            <div class=""item-actions-dropdown"">
                                <a class=""item-actions-toggle-btn"">
                                    <span class=""inactive"">
                                        <i class=""fa fa-cog""></i>
                                    </span>
                                    <span class=""active"">
                                        <i class=""fa fa-chevron-circle-right""></i>
                                    </span>
                                </a>
                                <div class=""item-actions-block"">
                                    <ul class=""item-actions-list"">
                                        <li>
                  ");
            WriteLiteral("                          <a class=\"remove\"");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 7257, "\"", 7305, 2);
            WriteAttributeValue("", 7264, "/Admin/ItemsCategories/Delete?id=", 7264, 33, true);
#line 155 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
WriteAttributeValue("", 7297, item.id, 7297, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(7306, 356, true);
            WriteLiteral(@" onclick=""return window.confirm('Are you sure?');"">
                                                <i class=""fa fa-trash-o "" title=""Xóa danh mục""></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class=""edit""");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 7662, "\"", 7708, 2);
            WriteAttributeValue("", 7669, "/Admin/ItemsCategories/Edit?id=", 7669, 31, true);
#line 160 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
WriteAttributeValue("", 7700, item.id, 7700, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(7709, 401, true);
            WriteLiteral(@">
                                                <i class=""fa fa-pencil"" title=""Sửa danh mục""></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
");
            EndContext();
#line 170 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
            }

#line default
#line hidden
            BeginContext(8125, 12, true);
            WriteLiteral("            ");
            EndContext();
            BeginContext(8138, 87, false);
#line 171 "G:\ASP.NET\project_banhang\project_banhang\Areas\Admin\Views\ItemsCategories\List.cshtml"
       Write(Html.PagedListPager(Model, page => Url.Action("List", "ItemsCategories", new { page })));

#line default
#line hidden
            EndContext();
            BeginContext(8225, 43, true);
            WriteLiteral("\r\n        </ul>\r\n    </div>\r\n</article>\r\n\r\n");
            EndContext();
            BeginContext(11001, 2, true);
            WriteLiteral("\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<X.PagedList.IPagedList<ItemsCategories>> Html { get; private set; }
    }
}
#pragma warning restore 1591
