#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Views\Home\quickViewProduct.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "36e808dbb08929dbbf32d4363caff6ed45019e2d"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_quickViewProduct), @"mvc.1.0.view", @"/Views/Home/quickViewProduct.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/quickViewProduct.cshtml", typeof(AspNetCore.Views_Home_quickViewProduct))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"36e808dbb08929dbbf32d4363caff6ed45019e2d", @"/Views/Home/quickViewProduct.cshtml")]
    public class Views_Home_quickViewProduct : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Views\Home\quickViewProduct.cshtml"
  
    ViewData["Title"] = "quickViewProduct";
    Layout = "~/Areas/Admin/Views/_share/_layout.cshtml";

#line default
#line hidden
            BeginContext(113, 7245, true);
            WriteLiteral(@"
    <div class=""quick-view-product"">
        <div class=""block-quickview primary_block row"">

            <div class=""product-left-column col-xs-12 col-sm-5 col-md-5 col-lg-5"">
                <div class=""clearfix image-block"">
                    <span class=""view_full_size"">
                        <a class=""img-product"" title="""" href=""#"">
                            <img id=""product-featured-image-quickview"" class=""img-responsive product-featured-image-quickview"" src=""//bizweb.dktcdn.net/thumb/large/100/329/122/products/a400-01.jpg"" alt=""quickview"">
                        </a>
                    </span>
                    <div class=""loading-imgquickview"" style=""display:none;""></div>
                </div>
                <div class=""more-view-wrapper clearfix"">
                    <div class=""thumbs_quickview thumbs_list_quickview"" id=""thumbs_list_quickview"">
                        <ul class=""product-photo-thumbs quickview-more-views-owlslider owl-loaded owl-drag"" id=""thumblist_quickvi");
            WriteLiteral(@"ew"" style=""visibility: visible;""><div class=""owl-stage-outer""><div class=""owl-stage"" style=""transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 338px;""><div class=""owl-item active"" style=""width: 84.333px;""><li class=""active""><a href=""javascript:void(0)"" data-imageid=""12488825"" ""="" "" data-zoom-image=""//bizweb.dktcdn.net/thumb/large/100/329/122/products/a400-01.jpg""><img src=""//bizweb.dktcdn.net/thumb/large/100/329/122/products/a400-01.jpg"" alt=""Office World"" style=""max-width:120px; max-height:120px;""></a></li></div><div class=""owl-item active"" style=""width: 84.333px;""><li><a href=""javascript:void(0)"" data-imageid=""12488825"" ""="" "" data-zoom-image=""//bizweb.dktcdn.net/thumb/large/100/329/122/products/a400-120.jpg""><img src=""//bizweb.dktcdn.net/thumb/large/100/329/122/products/a400-120.jpg"" alt=""Office World"" style=""max-width:120px; max-height:120px;""></a></li></div><div class=""owl-item active"" style=""width: 84.333px;""><li><a href=""javascript:void(0)"" data-imageid=""12488825"" ""="" "" data-zoom-");
            WriteLiteral(@"image=""//bizweb.dktcdn.net/thumb/large/100/329/122/products/a400-02.jpg""><img src=""//bizweb.dktcdn.net/thumb/large/100/329/122/products/a400-02.jpg"" alt=""Office World"" style=""max-width:120px; max-height:120px;""></a></li></div><div class=""owl-item active"" style=""width: 84.333px;""><li><a href=""javascript:void(0)"" data-imageid=""12488825"" ""="" "" data-zoom-image=""//bizweb.dktcdn.net/thumb/large/100/329/122/products/a400-03.jpg""><img src=""//bizweb.dktcdn.net/thumb/large/100/329/122/products/a400-03.jpg"" alt=""Office World"" style=""max-width:120px; max-height:120px;""></a></li></div></div></div><div class=""owl-nav""><div class=""owl-prev disabled""></div><div class=""owl-next""></div></div><div class=""owl-dots""><div class=""owl-dot active""><span></span></div><div class=""owl-dot""><span></span></div></div></ul>
                    </div>
                </div>
            </div>
            <div class=""product-center-column product-info product-item col-xs-5 col-sm-7 col-md-7 col-lg-7"" id=""product-12488825"">
              ");
            WriteLiteral(@"  <div class=""head-qv"">
                    <h3 class=""qwp-name""><a class=""text2line"" href=""/ssd-kingston-a400-sata-3-120gb-sa400s37120g"" title=""SSD Kingston A400 SATA 3 120GB SA400S37/120G"">SSD Kingston A400 SATA 3 120GB SA400S37/120G</a></h3>
                    <div class=""vend-qv"">
                        <div class=""left_vend"">
                            <span class=""vendor_""><span>Thương hiệu: </span>Kingston</span>
                            <span class=""line"">|</span>
                            Tình trạng: <span class=""soluong"">Còn hàng</span>
                        </div>

                    </div>
                </div>
                <div class=""quickview-info"">

                    <div class=""reviews_qv"">
                        <div class=""bizweb-product-reviews-badge"" data-id=""12488825""><div class=""bizweb-product-reviews-star"" data-score=""0"" data-number=""5"" title=""Not rated yet!"" style=""color: rgb(255, 190, 0);""><i data-alt=""1"" class=""star-off-png"" title=""Not rated yet!""></i");
            WriteLiteral(@">&nbsp;<i data-alt=""2"" class=""star-off-png"" title=""Not rated yet!""></i>&nbsp;<i data-alt=""3"" class=""star-off-png"" title=""Not rated yet!""></i>&nbsp;<i data-alt=""4"" class=""star-off-png"" title=""Not rated yet!""></i>&nbsp;<i data-alt=""5"" class=""star-off-png"" title=""Not rated yet!""></i><input name=""score"" type=""hidden"" readonly=""""></div><div><img src=""https://productreviews.sapoapps.vn//assets/images/user.png"" width=""18"" height=""17""></div></div>
                    </div>

                    <span class=""prices"">
                        <span class=""price"">550.000₫</span>
                        <del class=""old-price""></del>
                    </span>
                </div>
                <div class=""product-description"">
                    <div class=""rte text2line"">
                        Chuẩn SSD: 2.5 inches
                        Tốc độ đọc: 500 MB/s
                        Tốc độ ghi: 320 MB/s
                        Bảo hành chính hãng 3 năm 1 đổi 1
                        ...
          ");
            WriteLiteral(@"          </div>

                </div>

                <form action=""/cart/add"" method=""post"" enctype=""multipart/form-data"" class=""quick_option variants form-ajaxtocart"" id=""product-actions-12488825"">
                    <span class=""price-product-detail hidden"" style=""opacity: 0;"">
                        <span class=""""></span>
                    </span>


                    <div class=""quantity_wanted_p"">

                        <div class=""input_qty_qv"">
                            <span>Số lượng:</span>
                            <a class=""btn_num num_1 button button_qty"" onclick=""var result = document.getElementById('quantity-detail'); var qtyqv = result.value; if( !isNaN( qtyqv ) &amp;&amp; qtyqv > 1 ) result.value--;return false;"">-</a>
                            <input type=""text"" id=""quantity-detail"" name=""quantity"" value=""1"" onkeypress=""validate(event)"" onkeyup=""valid(this,'numbers')"" onblur=""valid(this,'numbers')"" class=""form-control prd_quantity"">
                          ");
            WriteLiteral(@"  <a class=""btn_num num_2 button button_qty"" onclick=""var result = document.getElementById('quantity-detail'); var qtyqv = result.value; if( !isNaN( qtyqv )) result.value++;return false;"">+</a>
                        </div>


                        <div class=""button_actions clearfix"">
                            <button type=""submit"" class=""btn btn_base ajax_addtocart btn_add_cart btn-cart add_to_cart add_to_cart_detail"">
                                <span class=""text_1"">MUA NGAY</span>
                                <span class=""text_2"">Giao hàng miễn phí tận nơi</span>
                            </button>

                        </div>
                    </div>
                    <div class=""total-price"" style=""display:none"">499.000₫</div>

                    <input type=""hidden"" name=""id"" value=""12488825""><input type=""hidden"" name=""variantId"" value=""21579213"">
                </form>


            </div>

        </div>
        <a title=""Close"" class=""quickview-close close-");
            WriteLiteral("window\" href=\"javascript:;\"><i class=\"fa   fa-times\"></i></a>\r\n    </div>\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
