#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\_quickView.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a59fde0dbba0278c7695802708cf70c5d932c14c"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views__shared__quickView), @"mvc.1.0.view", @"/Views/_shared/_quickView.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/_shared/_quickView.cshtml", typeof(AspNetCore.Views__shared__quickView))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a59fde0dbba0278c7695802708cf70c5d932c14c", @"/Views/_shared/_quickView.cshtml")]
    public class Views__shared__quickView : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("product-featured-image-quickview"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("img-responsive product-featured-image-quickview"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memory-Home/images/logo.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("alt", new global::Microsoft.AspNetCore.Html.HtmlString("quickview"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/Memory-Home/images/user.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("width", new global::Microsoft.AspNetCore.Html.HtmlString("18"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("height", new global::Microsoft.AspNetCore.Html.HtmlString("17"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\_quickView.cshtml"
  
    Layout = null;

#line default
#line hidden
            BeginContext(29, 603, true);
            WriteLiteral(@"
<div id=""quick-view-product"" class=""quickview-product"" style=""display:none;"">
    <div class=""quickview-overlay fancybox-overlay fancybox-overlay-fixed""></div>
    <div class=""quick-view-product""></div>
    <div id=""quickview-modal"" style=""display:none;"">
        <div class=""block-quickview primary_block row"">

            <div class=""product-left-column col-xs-12 col-sm-5 col-md-5 col-lg-5"">
                <div class=""clearfix image-block"">
                    <span class=""view_full_size"">
                        <a class=""img-product"" title="""" href=""#"">
                            ");
            EndContext();
            BeginContext(632, 151, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "029e35d9681c41cd8003c50a28eee374", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(783, 2105, true);
            WriteLiteral(@"
                        </a>
                    </span>
                    <div class=""loading-imgquickview"" style=""display:none;""></div>
                </div>
                <div class=""more-view-wrapper clearfix"">
                    <div class=""thumbs_quickview"" id=""thumbs_list_quickview"">
                        <ul class=""product-photo-thumbs quickview-more-views-owlslider"" id=""thumblist_quickview""></ul>
                    </div>
                </div>
            </div>
            <div class=""product-center-column product-info product-item col-xs-5 col-sm-7 col-md-7 col-lg-7"">
                <div class=""head-qv"">
                    <h3 class=""qwp-name"">abc</h3>
                    <div class=""vend-qv"">
                        <div class=""left_vend"">
                            <span class=""vendor_""></span>
                            <span class=""line"">|</span> Tình trạng: <span class=""soluong""></span>
                        </div>

                    </div>
             ");
            WriteLiteral(@"   </div>
                <div class=""quickview-info"">

                    <div class=""reviews_qv"">
                        <div class=""bizweb-product-reviews-badge"" data-id="""">
                            <div class=""bizweb-product-reviews-star"" data-score=""0"" data-number=""5"" title=""Not rated yet!"" style=""color: rgb(255, 190, 0);"">
                                <i data-alt=""1"" class=""star-off-png"" title=""Not rated yet!""></i>&nbsp;<i data-alt=""2"" class=""star-off-png"" title=""Not rated yet!""></i>&nbsp;<i data-alt=""3"" class=""star-off-png"" title=""Not rated yet!""></i>&nbsp;<i data-alt=""4""
                                                                                                                                                                                                                                                     class=""star-off-png"" title=""Not rated yet!""></i>&nbsp;<i data-alt=""5"" class=""star-off-png"" title=""Not rated yet!""></i><input name=""score"" type=""hidden"" readonly="""">
            ");
            WriteLiteral("                </div>\r\n                            <div>");
            EndContext();
            BeginContext(2888, 64, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "679dad4748174846b592fbd87441bb37", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_6);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(2952, 2483, true);
            WriteLiteral(@"</div>
                        </div>
                    </div>

                    <span class=""prices"">
                        <span class=""price""></span>
                        <del class=""old-price""></del>
                    </span>
                </div>
                <div class=""product-description"">
                    <div class=""rte text2line"">

                    </div>

                </div>

                <form action=""/cart/add"" method=""post"" enctype=""multipart/form-data"" class=""quick_option variants form-ajaxtocart"">
                    <span class=""price-product-detail hidden"" style=""opacity: 0;"">
                        <span class=""""></span>
                    </span>
                    <select name=""variantId"" class=""hidden"" style=""display:none""></select>

                    <div class=""quantity_wanted_p"">

                        <div class=""input_qty_qv"">
                            <span>Số lượng:</span>
                            <a class=""btn_num");
            WriteLiteral(@" num_1 button button_qty"" onclick=""var result = document.getElementById(&#39;quantity-detail&#39;); var qtyqv = result.value; if( !isNaN( qtyqv ) &amp;&amp; qtyqv &gt; 1 ) result.value--;return false;"">-</a>
                            <input type=""text"" id=""quantity-detail"" name=""quantity"" value=""1"" onkeypress=""validate(event)"" onkeyup=""valid(this,&#39;numbers&#39;)"" onblur=""valid(this,&#39;numbers&#39;)"" class=""form-control prd_quantity"">
                            <a class=""btn_num num_2 button button_qty"" onclick=""var result = document.getElementById(&#39;quantity-detail&#39;); var qtyqv = result.value; if( !isNaN( qtyqv )) result.value++;return false;"">+</a>
                        </div>


                        <div class=""button_actions clearfix"">
                            <button type=""submit"" class=""btn btn_base ajax_addtocart btn_add_cart btn-cart add_to_cart add_to_cart_detail"">
                                <span class=""text_1"">MUA NGAY</span>
                                <span ");
            WriteLiteral(@"class=""text_2"">Giao hàng miễn phí tận nơi</span>
                            </button>

                        </div>
                    </div>
                    <div class=""total-price"" style=""display:none"">0₫</div>

                </form>


            </div>

        </div>
        <a title=""Close"" class=""quickview-close close-window"" href=""javascript:;""><i class=""fa   fa-times""></i></a>
    </div>
</div>

");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
