#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "960dd5a389a3e268b5e47caa7abd188331e04eda"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views__shared_hotproducts), @"mvc.1.0.view", @"/Views/_shared/hotproducts.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/_shared/hotproducts.cshtml", typeof(AspNetCore.Views__shared_hotproducts))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 6 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
using project_banhang.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"960dd5a389a3e268b5e47caa7abd188331e04eda", @"/Views/_shared/hotproducts.cshtml")]
    public class Views__shared_hotproducts : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("img-responsive center-base"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("style", new global::Microsoft.AspNetCore.Html.HtmlString("height:370px;width:390px;"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
  
    Layout = null;

#line default
#line hidden
            BeginContext(29, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 7 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
   
    DataContext db = new DataContext();
    var _itemshot = db.ItemsCategories.OrderByDescending(tbl => tbl.id).ToList().Where(tbl=>tbl.hot==true);

#line default
#line hidden
            BeginContext(221, 149, true);
            WriteLiteral("\r\n<section class=\"awe-section-2\" id=\"home_block_2\">\r\n    <aside class=\"adv_bottom\">\r\n        <div class=\"container\">\r\n            <div class=\"row\">\r\n");
            EndContext();
#line 16 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
                 foreach (var item in _itemshot)
                {

#line default
#line hidden
            BeginContext(439, 225, true);
            WriteLiteral("                    <div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\">\r\n                        <div class=\"adv_bottom_inner\">\r\n                            <figure class=\"img_effect img_1\">\r\n                                <a");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 664, "\"", 697, 2);
            WriteAttributeValue("", 671, "/Product/Category/", 671, 18, true);
#line 21 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
WriteAttributeValue("", 689, item.id, 689, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginWriteAttribute("title", " title=\"", 698, "\"", 716, 1);
#line 21 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
WriteAttributeValue("", 706, item.name, 706, 10, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(717, 39, true);
            WriteLiteral(">\r\n                                    ");
            EndContext();
            BeginContext(756, 174, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "f5264d8fda814801ae86fc3a31eafcae", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            AddHtmlAttributeValue("", 801, "~/Upload/Category-Thum/", 801, 23, true);
#line 22 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
AddHtmlAttributeValue("", 824, item.thumnails, 824, 15, false);

#line default
#line hidden
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            BeginWriteTagHelperAttribute();
            WriteLiteral("~/Upload/Category-Thum/");
#line 22 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
                                                                                                                                                          Write(item.thumnails);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __tagHelperExecutionContext.AddHtmlAttribute("data-lazyload", Html.Raw(__tagHelperStringValueBuffer), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(930, 1, true);
            WriteLiteral(" ");
            EndContext();
            BeginContext(976, 139, true);
            WriteLiteral("\r\n                                </a>\r\n                            </figure>\r\n                        </div>\r\n                    </div>\r\n");
            EndContext();
#line 27 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
                }

#line default
#line hidden
            BeginContext(1134, 16, true);
            WriteLiteral("                ");
            EndContext();
            BeginContext(3080, 372, true);
            WriteLiteral(@"
            </div>
        </div>
    </aside>
</section>
<section class=""awe-section-3"" id=""home_block_3"">
    <section class=""section_hotdeal"">
        <div class=""container"">
            <div class=""row"">
                <div class=""content_hihi col-lg-12"">
                    <div class=""heading_hotdeal"">
                        <h2 class=""title-head"">
");
            EndContext();
#line 70 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
                               
                                DateTime dt = DateTime.Now;
                                DayOfWeek test = dt.DayOfWeek;
                                //dt=dt.Date;
                            

#line default
#line hidden
            BeginContext(3688, 140, true);
            WriteLiteral("                            <a href=\"/Flash-sale/\"></a><a href=\"/Flash-sale/\"><span class=\"color_main\" style=\"color:red\"></span>CYBER <text>");
            EndContext();
            BeginContext(3829, 4, false);
#line 75 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\hotproducts.cshtml"
                                                                                                                                       Write(test);

#line default
#line hidden
            EndContext();
            BeginContext(3833, 1224, true);
            WriteLiteral(@"</text></a>
                        </h2>
                    </div>

                    <div class=""border_wrap"">
                        <div class=""owl_product_comback "">
                            <div class=""product_comeback_wrap"">
                                <div class=""owl_product_item_content owl-carousel not-nav2 owl-loaded owl-drag"" data-dot=""false"" data-nav=""false"" data-lg-items=""5"" data-md-items=""4"" data-sm-items=""3"" data-xs-items=""2"" data-margin=""20"">

                                    <div class=""owl-stage-outer"">
                                        <div class=""owl-stage""></div>
                                    </div>
                                    <div class=""owl-nav disabled"">
                                        <div class=""owl-prev""> </div>
                                        <div class=""owl-next""> </div>
                                    </div>
                                    <div class=""owl-dots disabled""></div>
                            ");
            WriteLiteral("    </div>\r\n\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </section>\r\n</section>\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
