#pragma checksum "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "28228ad25fb9a5536c737dd587e10ecf04afc7b9"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views__shared_ListProducts), @"mvc.1.0.view", @"/Views/_shared/ListProducts.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/_shared/ListProducts.cshtml", typeof(AspNetCore.Views__shared_ListProducts))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
#line 6 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml"
using System.Linq;

#line default
#line hidden
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 5 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml"
using project_banhang.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"28228ad25fb9a5536c737dd587e10ecf04afc7b9", @"/Views/_shared/ListProducts.cshtml")]
    public class Views__shared_ListProducts : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml"
  
    Layout = null;

#line default
#line hidden
#line 7 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml"
  
    //kkhoiwr tạo đối tượng thao tác csdll
    DataContext db = new DataContext();
    //lấy danh sách của itemscategories
    var itemscategories = db.ItemsCategories.OrderByDescending(tbl => tbl.name).ToList();
    var itemslist = db.ItemsList.OrderByDescending(tbl => tbl.name);
    //var tbl_join=from a in itemscategories join b in itemslist on a.id equals b.id_category join c in subcategories on 

#line default
#line hidden
            BeginContext(498, 2404, true);
            WriteLiteral(@"
    <div class=""wrap_main"">
        <div class=""container"">
            <div class=""row"">
                <div class=""col-lg-3 col-md-3 col-sm-12 col-xs-12 col-mega"">
                    <div class=""menu_mega"">
                        <div class=""title_menu"">
                            <span class=""title_"">Danh mục sản phẩm</span>
                            <span class=""nav_button""><span><i class=""fa fa-bars"" aria-hidden=""true""></i></span></span>
                        </div>
                        <div class=""list_menu_header menu_all_site col-lg-3 col-md-3 hidden-sm hidden-xs"">
                            <ul class=""ul_menu site-nav-vetical"">
                                <li class=""nav_item lv1 li_check"">
                                    <a target=""_blank"" href=""https://www.memoryzone.com.vn/best-seller"" title=""BEST SELLER"">
                                        BEST SELLER
                                        <i class=""fa fa-angle-right""></i>
                                ");
            WriteLiteral(@"    </a>
                                    <ul class=""ul_content_right_1 row"">
                                        <li class=""nav_item lv2 col-lg-3 col-md-3""><a target=""_blank"" href=""https://www.memoryzone.com.vn/top-10-ssd"" title=""TOP SSD"">TOP SSD</a></li>


                                        <li class=""nav_item lv2 col-lg-3 col-md-3""><a target=""_blank"" href=""https://www.memoryzone.com.vn/top-10-usb"" title=""Top USB"">Top USB</a></li>



                                        <li class=""nav_item lv2 col-lg-3 col-md-3""><a target=""_blank"" href=""https://www.memoryzone.com.vn/top-10-ssd"" title=""Top SSD"">Top SSD</a></li>



                                        <li class=""nav_item lv2 col-lg-3 col-md-3""><a target=""_blank"" href=""https://www.memoryzone.com.vn/top-10-microsd"" title=""Top microSD"">Top microSD</a></li>



                                        <li class=""nav_item lv2 col-lg-3 col-md-3""><a target=""_blank"" href=""https://www.memoryzone.com.vn/top-o-cung-di-dong"" title=""Top ổ ");
            WriteLiteral(@"cứng di động"">Top ổ cứng di động</a></li>



                                        <li class=""nav_item lv2 col-lg-3 col-md-3""><a target=""_blank"" href=""https://www.memoryzone.com.vn/the-class-10-u3"" title=""Thẻ nhớ Class 10 U3"">Thẻ nhớ Class 10 U3</a></li>


                                    </ul>
                                </li>




");
            EndContext();
#line 61 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml"
                                 foreach (var item in itemscategories)
                                {

#line default
#line hidden
            BeginContext(3009, 130, true);
            WriteLiteral("                                    <li class=\"nav_item lv1 li_check\">\r\n                                        <a target=\"_blank\"");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 3139, "\"", 3172, 2);
            WriteAttributeValue("", 3146, "/Product/Category/", 3146, 18, true);
#line 64 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml"
WriteAttributeValue("", 3164, item.id, 3164, 8, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginWriteAttribute("title", " title=\"", 3173, "\"", 3191, 1);
#line 64 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml"
WriteAttributeValue("", 3181, item.name, 3181, 10, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(3192, 47, true);
            WriteLiteral(">\r\n                                            ");
            EndContext();
            BeginContext(3240, 9, false);
#line 65 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml"
                                       Write(item.name);

#line default
#line hidden
            EndContext();
            BeginContext(3249, 129, true);
            WriteLiteral("\r\n                                            <i class=\"fa fa-angle-right\"></i>\r\n                                        </a>\r\n\r\n");
            EndContext();
            BeginContext(5482, 43, true);
            WriteLiteral("                                    </li>\r\n");
            EndContext();
#line 96 "G:\ASP.NET\project_banhang\project_banhang\Views\_shared\ListProducts.cshtml"
                                }

#line default
#line hidden
            BeginContext(5560, 10, true);
            WriteLiteral("\r\n\r\n\r\n\r\n\r\n");
            EndContext();
            BeginContext(80452, 3335, true);
            WriteLiteral(@"

                            </ul>
                            <script>
                                $(document).ready(function () {
                                    $('.open-close').on('click', function (e) {
                                        e.preventDefault();
                                        var $this = $(this);
                                        $this.parents('.li-has-subs').find('.submenu').stop().slideToggle();
                                        $(this).toggleClass('active')
                                        return false;
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
                <div class=""col-lg-9 col-md-9 hidden-xs hidden-sm"">
                    <div class=""bg-header-nav"">
                        <div>
                            <div class=""row row-noGutter-2"">
                              ");
            WriteLiteral(@"  <nav class=""header-nav"">
                                    <ul class=""item_big"">







                                        <li class=""nav-item"">
                                            <a  class=""a-img"" href=""/Home/"">
                                                <span>TRANG CHỦ</span>
                                                <span class=""label_"">

                                                    <i class=""label ""></i>

                                                </span>
                                            </a>
                                        </li>
                                        <li class=""nav-item "">
                                            <a target=""_blank"" class=""a-img"" href=""#"">
                                                <span>THANH TOÁN</span>
                                                <span class=""label_"">

                                                    <i class=""label ""></i>

                             ");
            WriteLiteral(@"                   </span>
                                            </a>
                                        </li>
                                        <li class=""nav-item "">
                                            <a target=""_blank"" class=""a-img"" href=""#"">
                                                <span>CHÍNH SÁCH GIAO HÀNG</span>
                                                <span class=""label_"">

                                                </span>
                                            </a>
                                        </li>
                                        <li class=""nav-item "">
                                            <a target=""_blank"" class=""a-img"" href=""#"">
                                                <span>LIÊN HỆ</span>
                                                <span class=""label_"">

                                                </span>
                                            </a>
                                   ");
            WriteLiteral(@"     </li>

                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
